/* =========================================================
   Diccionario Español / English Dictionary — herramienta de
   consulta (no es un juego: sin rondas, estrellas ni XP).
   Accesible desde la pantalla de etapas (etapaMap), pensada
   como apoyo transversal a todas las etapas escolares.

   Contenido 100% curado dentro de la app (sin API externa):
   una API de diccionario no garantiza contenido apto para
   niños, requeriría conexión permanente y rompería la regla
   de "cero dependencias" del proyecto. El banco es vocabulario
   escolar de uso frecuente, con definiciones simples en
   español de Chile y ejemplos cortos.

   La voz reutiliza speak() de js/audio.js: español por defecto
   para el Diccionario Español, y speak(texto, 'en') para el
   English Dictionary (mismo mecanismo speakLang que usa
   content/ingles.js desde 5° básico).

   El botón 🔊 usa onclick="diccSpeak(i)" con un índice sobre la
   lista visible (module state), en vez de incrustar el texto en
   el atributo onclick — así ninguna definición puede romper el
   HTML por comillas (la misma restricción documentada de
   speakText en mcEngine.js, resuelta aquí por diseño).
   ========================================================= */
import { speak } from '../audio.js';

const DICC_ES = [
  { p:'Abanico', t:'sustantivo', d:'Objeto que se agita con la mano para dar aire y refrescarse.', e:'Se abanicó con un abanico de papel.' },
  { p:'Abeja', t:'sustantivo', d:'Insecto volador de rayas amarillas y negras que fabrica miel y ayuda a las flores a reproducirse.', e:'La abeja vuela de flor en flor.' },
  { p:'Abogado', t:'sustantivo', d:'Persona que estudia y aplica las leyes para defender o asesorar a otras personas.', e:'La abogada explicó el contrato con calma.' },
  { p:'Abrazo', t:'sustantivo', d:'Gesto de cariño que consiste en rodear a alguien con los brazos.', e:'Le dio un abrazo a su abuela al llegar.' },
  { p:'Abuela', t:'sustantivo', d:'Madre de la madre o del padre de una persona.', e:'Mi abuela cuenta historias increíbles.' },
  { p:'Abuelo', t:'sustantivo', d:'Padre de la madre o del padre de una persona.', e:'Mi abuelo me enseñó a pescar.' },
  { p:'Acuario', t:'sustantivo', d:'Recipiente o edificio donde se mantienen peces y otros animales acuáticos para observarlos.', e:'Visitamos el acuario y vimos tiburones.' },
  { p:'Adivinar', t:'verbo', d:'Descubrir algo sin saberlo con certeza, a partir de pistas.', e:'Intenté adivinar qué regalo me darían.' },
  { p:'Agricultor', t:'sustantivo', d:'Persona que cultiva la tierra para producir alimentos.', e:'El agricultor cosechó trigo en verano.' },
  { p:'Agua', t:'sustantivo', d:'Líquido transparente y sin sabor que beben los seres vivos y cubre gran parte de la Tierra.', e:'Toma agua durante todo el día.' },
  { p:'Águila', t:'sustantivo', d:'Ave grande de rapiña, de vista muy aguda y vuelo poderoso.', e:'El águila voló en círculos buscando su presa.' },
  { p:'Alegría', t:'sustantivo', d:'Emoción que sentimos cuando algo nos gusta o nos hace felices.', e:'Saltó de alegría con la noticia.' },
  { p:'Alfombra', t:'sustantivo', d:'Tejido grueso que cubre el suelo de una habitación.', e:'Nos sentamos sobre la alfombra a jugar.' },
  { p:'Almohada', t:'sustantivo', d:'Objeto blando donde se apoya la cabeza para dormir.', e:'Cambié la funda de mi almohada.' },
  { p:'Alpaca', t:'sustantivo', d:'Animal andino parecido a la llama, de lana suave y abundante.', e:'La alpaca pastaba en la altura de los Andes.' },
  { p:'Amable', t:'adjetivo', d:'Que trata a los demás con cariño y respeto.', e:'El vecino fue muy amable con nosotros.' },
  { p:'Amanecer', t:'sustantivo', d:'Momento del día en que empieza a salir el sol.', e:'Nos levantamos temprano para ver el amanecer.' },
  { p:'Amistad', t:'sustantivo', d:'Cariño y confianza entre personas que se quieren y se acompañan.', e:'Su amistad comenzó en el colegio.' },
  { p:'Amor', t:'sustantivo', d:'Sentimiento profundo de cariño y afecto hacia alguien o algo.', e:'El amor de una familia da mucha fuerza.' },
  { p:'Ancho', t:'adjetivo', d:'Que tiene mucha distancia de un lado a otro.', e:'El río se hace más ancho cerca del mar.' },
  { p:'Anillo', t:'sustantivo', d:'Aro pequeño, generalmente de metal, que se usa como adorno en un dedo.', e:'Le regaló un anillo de plata.' },
  { p:'Antena', t:'sustantivo', d:'Objeto que recibe o envía señales, usado en radios, televisores y celulares.', e:'La antena de la casa capta muchos canales.' },
  { p:'Apagar', t:'verbo', d:'Hacer que algo deje de funcionar o de dar luz.', e:'Hay que apagar la luz al salir.' },
  { p:'Aprender', t:'verbo', d:'Adquirir conocimientos o habilidades nuevas.', e:'Me gusta aprender cosas nuevas cada día.' },
  { p:'Araña', t:'sustantivo', d:'Animal de ocho patas que teje telarañas para atrapar insectos.', e:'La araña tejió su tela en la ventana.' },
  { p:'Árbol', t:'sustantivo', d:'Planta grande con tronco de madera, ramas y hojas.', e:'El árbol del patio da mucha sombra.' },
  { p:'Arcoíris', t:'sustantivo', d:'Arco de colores que aparece en el cielo cuando el sol ilumina la lluvia.', e:'Después de la lluvia salió un arcoíris.' },
  { p:'Arena', t:'sustantivo', d:'Conjunto de granitos muy pequeños que cubre playas y desiertos.', e:'Construimos un castillo de arena.' },
  { p:'Aroma', t:'sustantivo', d:'Olor agradable que desprende algo.', e:'El aroma del pan recién hecho llenó la cocina.' },
  { p:'Arquitecto', t:'sustantivo', d:'Persona que diseña y planifica edificios y otras construcciones.', e:'La arquitecta diseñó una casa con muchas ventanas.' },
  { p:'Arroz', t:'sustantivo', d:'Cereal pequeño y blanco que se cocina en agua y se come como acompañamiento.', e:'Comimos arroz con pollo.' },
  { p:'Artista', t:'sustantivo', d:'Persona que crea obras de arte, como pinturas, música o esculturas.', e:'La artista pintó un mural enorme.' },
  { p:'Astronauta', t:'sustantivo', d:'Persona entrenada para viajar y trabajar en el espacio.', e:'El astronauta flotaba dentro de la nave.' },
  { p:'Atardecer', t:'sustantivo', d:'Momento del día en que el sol se está poniendo.', e:'El atardecer pintó el cielo de naranjo.' },
  { p:'Auto', t:'sustantivo', d:'Vehículo con motor y cuatro ruedas que se usa para transportar personas.', e:'Fuimos en auto hasta la playa.' },
  { p:'Aventura', t:'sustantivo', d:'Experiencia emocionante y fuera de lo común.', e:'El libro cuenta una aventura en la selva.' },
  { p:'Avión', t:'sustantivo', d:'Vehículo con alas que vuela por el aire y transporta personas o cosas.', e:'Viajamos en avión a Isla de Pascua.' },
  { p:'Ayudar', t:'verbo', d:'Hacer algo por otra persona para que le resulte más fácil.', e:'Voy a ayudar a mi hermana con su tarea.' },
  { p:'Balcón', t:'sustantivo', d:'Espacio pequeño que sobresale de una ventana o piso, con baranda.', e:'Regamos las plantas del balcón.' },
  { p:'Ballena', t:'sustantivo', d:'Mamífero marino gigante, el animal más grande que existe.', e:'La ballena azul es más grande que cualquier dinosaurio conocido.' },
  { p:'Bandera', t:'sustantivo', d:'Tela de colores y símbolos que representa a un país u organización.', e:'Izamos la bandera de Chile el 18 de septiembre.' },
  { p:'Barco', t:'sustantivo', d:'Vehículo que flota y sirve para viajar o transportar cosas por el agua.', e:'El barco cruzó el canal muy temprano.' },
  { p:'Bebé', t:'sustantivo', d:'Niño o niña recién nacido o de muy poca edad.', e:'El bebé durmió toda la tarde.' },
  { p:'Beso', t:'sustantivo', d:'Gesto de cariño que se hace tocando con los labios.', e:'Le dio un beso de buenas noches.' },
  { p:'Biblioteca', t:'sustantivo', d:'Lugar donde se guardan y prestan libros para leer y estudiar.', e:'Pedí dos cuentos en la biblioteca.' },
  { p:'Billete', t:'sustantivo', d:'Papel moneda que se usa para pagar.', e:'Pagó con un billete de mil pesos.' },
  { p:'Bombero', t:'sustantivo', d:'Persona que apaga incendios y ayuda en emergencias.', e:'El bombero rescató al gato del árbol.' },
  { p:'Bombilla', t:'sustantivo', d:'Objeto de vidrio que produce luz al conectarse a la electricidad.', e:'Cambiamos la bombilla quemada del pasillo.' },
  { p:'Bondad', t:'sustantivo', d:'Cualidad de las personas que hacen el bien y tratan bien a los demás.', e:'Su bondad se nota en cómo cuida a sus amigos.' },
  { p:'Bosque', t:'sustantivo', d:'Lugar con muchos árboles, plantas y animales.', e:'Caminamos por el bosque de araucarias.' },
  { p:'Botella', t:'sustantivo', d:'Recipiente de vidrio o plástico, angosto en el cuello, que sirve para guardar líquidos.', e:'Llené la botella con agua fresca.' },
  { p:'Brazo', t:'sustantivo', d:'Parte del cuerpo que va desde el hombro hasta la mano.', e:'Levantó el brazo para preguntar.' },
  { p:'Brújula', t:'sustantivo', d:'Instrumento con una aguja que siempre apunta al norte y sirve para orientarse.', e:'Con la brújula encontramos el camino.' },
  { p:'Buscar', t:'verbo', d:'Intentar encontrar algo o a alguien.', e:'Vamos a buscar el libro en la estantería.' },
  { p:'Caballo', t:'sustantivo', d:'Animal grande de cuatro patas que se usa para montar o tirar carretas.', e:'El caballo galopó por el campo.' },
  { p:'Cabeza', t:'sustantivo', d:'Parte superior del cuerpo donde están el cerebro, los ojos y la boca.', e:'Usa casco para proteger la cabeza.' },
  { p:'Calendario', t:'sustantivo', d:'Sistema que organiza los días, semanas y meses del año.', e:'Marcamos su cumpleaños en el calendario.' },
  { p:'Calor', t:'sustantivo', d:'Sensación de temperatura alta; energía que hace que las cosas se calienten.', e:'En el desierto hace mucho calor de día.' },
  { p:'Camino', t:'sustantivo', d:'Terreno o ruta por donde se transita de un lugar a otro.', e:'Seguimos el camino hasta la cascada.' },
  { p:'Campana', t:'sustantivo', d:'Objeto de metal que suena cuando se lo golpea, usado para avisar algo.', e:'La campana del colegio anunció el recreo.' },
  { p:'Canción', t:'sustantivo', d:'Composición musical hecha para ser cantada.', e:'Aprendimos una canción nueva en clases.' },
  { p:'Canela', t:'sustantivo', d:'Especia aromática que se obtiene de la corteza de un árbol.', e:'El postre llevaba un toque de canela.' },
  { p:'Cangrejo', t:'sustantivo', d:'Animal marino de caparazón duro y dos grandes pinzas.', e:'El cangrejo caminó de lado por la arena.' },
  { p:'Capital', t:'sustantivo', d:'Ciudad principal de un país o región, donde suele estar el gobierno.', e:'Santiago es la capital de Chile.' },
  { p:'Cariño', t:'sustantivo', d:'Sentimiento de amor y ternura hacia alguien.', e:'Trata a su mascota con mucho cariño.' },
  { p:'Casa', t:'sustantivo', d:'Lugar donde vive una persona o una familia.', e:'Mi casa queda cerca de la plaza.' },
  { p:'Cascada', t:'sustantivo', d:'Caída de agua desde una altura, generalmente en un río o arroyo.', e:'Nos bañamos cerca de la cascada.' },
  { p:'Castillo', t:'sustantivo', d:'Construcción grande y fortificada, antiguamente usada como vivienda y defensa.', e:'El castillo tenía torres muy altas.' },
  { p:'Cebolla', t:'sustantivo', d:'Verdura de bulbo redondo y sabor fuerte, muy usada para cocinar.', e:'El pino de la empanada lleva cebolla picada.' },
  { p:'Cebra', t:'sustantivo', d:'Animal parecido al caballo, con rayas blancas y negras.', e:'La cebra vive en manadas en África.' },
  { p:'Cepillo', t:'sustantivo', d:'Instrumento con cerdas que sirve para limpiar o peinar.', e:'Uso un cepillo distinto para el pelo y para los dientes.' },
  { p:'Cerdo', t:'sustantivo', d:'Animal de granja de cuerpo rosado y hocico chato.', e:'El cerdo se revolcó en el barro.' },
  { p:'Cerebro', t:'sustantivo', d:'Órgano dentro de la cabeza que controla el cuerpo y permite pensar.', e:'El cerebro guarda todos nuestros recuerdos.' },
  { p:'Cielo', t:'sustantivo', d:'Espacio que se ve sobre la Tierra, donde están el sol, la luna y las nubes.', e:'El cielo se puso naranjo al atardecer.' },
  { p:'Ciencia', t:'sustantivo', d:'Conjunto de conocimientos que explican cómo funciona el mundo, obtenidos observando y experimentando.', e:'La ciencia estudia desde las estrellas hasta las células.' },
  { p:'Cinturón', t:'sustantivo', d:'Correa que se usa alrededor de la cintura para sujetar la ropa o para seguridad.', e:'Abróchate el cinturón de seguridad.' },
  { p:'Ciudad', t:'sustantivo', d:'Lugar grande con muchas calles, edificios y personas viviendo juntas.', e:'Santiago es la ciudad más poblada de Chile.' },
  { p:'Ciudadano', t:'sustantivo', d:'Persona que pertenece a un país y tiene derechos y deberes en él.', e:'Cada ciudadano puede votar en las elecciones.' },
  { p:'Cocinar', t:'verbo', d:'Preparar alimentos para comerlos.', e:'Aprendimos a cocinar pan amasado.' },
  { p:'Cofre', t:'sustantivo', d:'Caja resistente, a veces decorada, que sirve para guardar objetos valiosos.', e:'El cofre del tesoro estaba escondido en la isla.' },
  { p:'Colegio', t:'sustantivo', d:'Establecimiento donde se enseña a los estudiantes; sinónimo de escuela.', e:'Mi colegio tiene una cancha grande.' },
  { p:'Colibrí', t:'sustantivo', d:'Ave muy pequeña que puede volar hacia atrás y bate las alas muy rápido.', e:'El colibrí picoteó el néctar de la flor.' },
  { p:'Colina', t:'sustantivo', d:'Elevación del terreno más baja que una montaña.', e:'Subimos la colina para ver la puesta de sol.' },
  { p:'Columpio', t:'sustantivo', d:'Asiento colgante que se mece hacia adelante y atrás, usado para jugar.', e:'Se subió al columpio del parque.' },
  { p:'Comida', t:'sustantivo', d:'Alimento que se consume para nutrirse.', e:'La comida ya estaba lista para el almuerzo.' },
  { p:'Compartir', t:'verbo', d:'Dar parte de lo que uno tiene a otras personas.', e:'Me gusta compartir mi colación.' },
  { p:'Computador', t:'sustantivo', d:'Máquina electrónica que procesa información y permite trabajar, jugar o buscar datos.', e:'Hicimos la tarea en el computador.' },
  { p:'Comunidad', t:'sustantivo', d:'Grupo de personas que viven en un mismo lugar y comparten intereses.', e:'Toda la comunidad ayudó a limpiar la plaza.' },
  { p:'Cóndor', t:'sustantivo', d:'Ave grande de alas anchas que vive en la cordillera. Es el ave nacional de Chile.', e:'El cóndor voló muy alto sobre los Andes.' },
  { p:'Conejo', t:'sustantivo', d:'Animal pequeño de orejas largas que salta y come pasto.', e:'El conejo escondió una zanahoria.' },
  { p:'Confianza', t:'sustantivo', d:'Seguridad que se siente al creer en alguien o en algo.', e:'La confianza es la base de una buena amistad.' },
  { p:'Continente', t:'sustantivo', d:'Cada una de las grandes extensiones de tierra del planeta, como América o Asia.', e:'Chile está en el continente americano.' },
  { p:'Copihue', t:'sustantivo', d:'Flor roja o blanca, trepadora, que es la flor nacional de Chile.', e:'El copihue crece en los bosques del sur.' },
  { p:'Corazón', t:'sustantivo', d:'Órgano que bombea la sangre por todo el cuerpo.', e:'El corazón late más rápido cuando corremos.' },
  { p:'Cordillera', t:'sustantivo', d:'Conjunto de montañas unidas entre sí. En Chile, la más conocida es la cordillera de los Andes.', e:'La cordillera se ve nevada en invierno.' },
  { p:'Cuaderno', t:'sustantivo', d:'Conjunto de hojas de papel unidas donde se escribe o dibuja.', e:'Anoté la tarea en mi cuaderno.' },
  { p:'Cueca', t:'sustantivo', d:'Baile tradicional chileno que se baila en pareja agitando un pañuelo.', e:'Bailaron cueca en las Fiestas Patrias.' },
  { p:'Cuento', t:'sustantivo', d:'Relato breve, generalmente de ficción, con personajes y una historia.', e:'Me leyó un cuento antes de dormir.' },
  { p:'Cuidar', t:'verbo', d:'Poner atención y esfuerzo en proteger a alguien o algo.', e:'Debemos cuidar el medioambiente.' },
  { p:'Curioso', t:'adjetivo', d:'Que tiene ganas de conocer, descubrir o entender cosas nuevas.', e:'Es un niño curioso: todo lo pregunta.' },
  { p:'Dedo', t:'sustantivo', d:'Cada una de las partes alargadas al final de la mano o el pie.', e:'Se pintó las uñas de los dedos.' },
  { p:'Delfín', t:'sustantivo', d:'Animal marino inteligente que respira aire y nada en grupos.', e:'El delfín saltó fuera del agua.' },
  { p:'Dentista', t:'sustantivo', d:'Persona que cuida y trata los dientes y encías.', e:'El dentista revisó mis dientes.' },
  { p:'Deporte', t:'sustantivo', d:'Actividad física que se practica siguiendo reglas, muchas veces en competencia.', e:'El fútbol es un deporte muy popular en Chile.' },
  { p:'Desafío', t:'sustantivo', d:'Reto u obstáculo que exige esfuerzo para superarlo.', e:'Terminar la carrera fue un gran desafío.' },
  { p:'Descubrir', t:'verbo', d:'Encontrar o conocer algo que no se conocía.', e:'Al mover la piedra descubrimos un caracol.' },
  { p:'Desierto', t:'sustantivo', d:'Lugar muy seco con poca lluvia y vegetación escasa. El desierto de Atacama es el más árido del mundo.', e:'Casi nunca llueve en el desierto.' },
  { p:'Destino', t:'sustantivo', d:'Lugar al que alguien se dirige, o el rumbo que sigue su vida.', e:'Nuestro destino de vacaciones fue el norte.' },
  { p:'Diamante', t:'sustantivo', d:'Piedra preciosa muy dura y brillante.', e:'El anillo tenía un pequeño diamante.' },
  { p:'Dibujar', t:'verbo', d:'Representar algo con líneas y formas sobre un papel u otra superficie.', e:'Voy a dibujar a mi familia.' },
  { p:'Diccionario', t:'sustantivo', d:'Libro o herramienta donde se explica qué significan las palabras, ordenadas alfabéticamente.', e:'Busqué la palabra en el diccionario.' },
  { p:'Dinero', t:'sustantivo', d:'Monedas y billetes que se usan para comprar cosas.', e:'Ahorró dinero para comprar una bicicleta.' },
  { p:'Disfraz', t:'sustantivo', d:'Ropa especial que se usa para parecer otro personaje.', e:'Se puso un disfraz de superhéroe.' },
  { p:'Docena', t:'sustantivo', d:'Grupo de doce unidades de algo.', e:'Compramos una docena de huevos.' },
  { p:'Dormir', t:'verbo', d:'Descansar con los ojos cerrados, sin estar despierto.', e:'Hay que dormir bien antes del colegio.' },
  { p:'Duda', t:'sustantivo', d:'Falta de certeza sobre algo.', e:'Levantó la mano porque tenía una duda.' },
  { p:'Edificio', t:'sustantivo', d:'Construcción grande, generalmente de varios pisos.', e:'El edificio tiene veinte pisos.' },
  { p:'Educación', t:'sustantivo', d:'Proceso de aprender y enseñar conocimientos, habilidades y valores.', e:'La educación abre muchas puertas.' },
  { p:'Ejemplo', t:'sustantivo', d:'Caso o hecho que sirve para explicar o ilustrar algo.', e:'La profesora dio un ejemplo en la pizarra.' },
  { p:'Elefante', t:'sustantivo', d:'Animal terrestre enorme, con trompa larga y orejas grandes.', e:'El elefante usa su trompa para tomar agua.' },
  { p:'Emoción', t:'sustantivo', d:'Reacción intensa que sentimos frente a algo, como alegría, miedo o sorpresa.', e:'No pudo ocultar su emoción al ganar.' },
  { p:'Empanada', t:'sustantivo', d:'Comida chilena hecha de masa rellena, generalmente con pino (carne, cebolla y huevo), horneada o frita.', e:'Comimos empanadas de pino en Fiestas Patrias.' },
  { p:'Empresa', t:'sustantivo', d:'Organización que produce o vende bienes o servicios.', e:'Su padre trabaja en una empresa de tecnología.' },
  { p:'Energía', t:'sustantivo', d:'Capacidad para moverse, trabajar o producir cambios. La luz y el calor son formas de energía.', e:'El sol nos entrega energía todos los días.' },
  { p:'Enfermera', t:'sustantivo', d:'Persona que cuida y atiende a los enfermos en un hospital o consultorio.', e:'La enfermera midió mi temperatura.' },
  { p:'Enojo', t:'sustantivo', d:'Sentimiento de molestia o rabia frente a algo que no nos gusta.', e:'Contó hasta diez para calmar su enojo.' },
  { p:'Enseñar', t:'verbo', d:'Transmitir conocimientos o habilidades a otra persona.', e:'Le gusta enseñar matemáticas a sus compañeros.' },
  { p:'Equipo', t:'sustantivo', d:'Grupo de personas que trabajan o juegan juntas por un objetivo común.', e:'Nuestro equipo ganó el campeonato.' },
  { p:'Escalera', t:'sustantivo', d:'Serie de escalones que permite subir o bajar entre dos niveles.', e:'Subió la escalera de dos en dos.' },
  { p:'Escritor', t:'sustantivo', d:'Persona que se dedica a escribir libros u otras obras.', e:'La escritora presentó su nuevo libro.' },
  { p:'Escuela', t:'sustantivo', d:'Lugar donde los niños y niñas van a aprender con sus profesores.', e:'La escuela queda a dos cuadras.' },
  { p:'Esfuerzo', t:'sustantivo', d:'Energía y empeño que se pone para lograr algo, aunque cueste.', e:'Con esfuerzo terminó todo el trabajo.' },
  { p:'Espejo', t:'sustantivo', d:'Superficie que refleja la imagen de lo que tiene delante.', e:'Se miró en el espejo antes de salir.' },
  { p:'Estación', t:'sustantivo', d:'Lugar donde se detienen los trenes o buses para que suban y bajen pasajeros; también, cada una de las cuatro partes del año.', e:'Esperamos el tren en la estación.' },
  { p:'Estrella', t:'sustantivo', d:'Cuerpo del espacio que brilla con luz propia. El Sol es una estrella.', e:'Anoche vimos una estrella muy brillante.' },
  { p:'Estudiar', t:'verbo', d:'Dedicar tiempo a aprender o comprender algo.', e:'Hoy voy a estudiar para la prueba.' },
  { p:'Exposición', t:'sustantivo', d:'Muestra pública de objetos, obras de arte u otra información.', e:'Fuimos a una exposición de fotografías.' },
  { p:'Fábrica', t:'sustantivo', d:'Lugar donde se producen objetos en grandes cantidades usando máquinas.', e:'La fábrica produce miles de zapatos al mes.' },
  { p:'Familia', t:'sustantivo', d:'Grupo de personas unidas por parentesco o cariño que se cuidan entre sí.', e:'Mi familia almuerza junta los domingos.' },
  { p:'Farmacia', t:'sustantivo', d:'Lugar donde se venden medicamentos.', e:'Compramos las pastillas en la farmacia.' },
  { p:'Felicidad', t:'sustantivo', d:'Estado de ánimo de quien se siente pleno y contento.', e:'La felicidad se nota en su sonrisa.' },
  { p:'Feria', t:'sustantivo', d:'Mercado al aire libre donde se venden frutas, verduras y otros productos.', e:'Compramos verduras frescas en la feria.' },
  { p:'Fiesta', t:'sustantivo', d:'Reunión de personas para celebrar algo con alegría.', e:'Organizamos una fiesta sorpresa para su cumpleaños.' },
  { p:'Flor', t:'sustantivo', d:'Parte colorida de muchas plantas, de donde nacen los frutos y las semillas.', e:'El copihue es la flor nacional de Chile.' },
  { p:'Fósil', t:'sustantivo', d:'Resto de un ser vivo muy antiguo que quedó conservado en la roca.', e:'Encontraron un fósil de dinosaurio en el desierto.' },
  { p:'Frío', t:'adjetivo', d:'Que tiene poco calor o baja temperatura.', e:'El agua del mar está muy fría en invierno.' },
  { p:'Frontera', t:'sustantivo', d:'Línea que separa un país o territorio de otro.', e:'Cruzamos la frontera para llegar a Argentina.' },
  { p:'Fruta', t:'sustantivo', d:'Alimento que dan algunas plantas, generalmente dulce, como la manzana o la frutilla.', e:'De colación traje fruta picada.' },
  { p:'Fuego', t:'sustantivo', d:'Luz y calor que se producen cuando algo se quema.', e:'El fuego de la chimenea calienta la casa.' },
  { p:'Fuerte', t:'adjetivo', d:'Que tiene mucha fuerza o resistencia.', e:'El elefante es un animal muy fuerte.' },
  { p:'Fútbol', t:'sustantivo', d:'Deporte de equipo que se juega pateando una pelota para meter goles.', e:'Jugamos fútbol todos los sábados.' },
  { p:'Galaxia', t:'sustantivo', d:'Conjunto enorme de estrellas, planetas, gas y polvo. La nuestra se llama Vía Láctea.', e:'Nuestra galaxia tiene millones de estrellas.' },
  { p:'Gaviota', t:'sustantivo', d:'Ave marina blanca y gris que vuela cerca de la costa.', e:'La gaviota voló sobre el muelle.' },
  { p:'Generoso', t:'adjetivo', d:'Que comparte lo que tiene y ayuda sin esperar algo a cambio.', e:'Fue generoso y repartió sus dulces.' },
  { p:'Geografía', t:'sustantivo', d:'Ciencia que estudia el territorio, el relieve, el clima y la población de un lugar.', e:'En geografía aprendimos sobre los continentes.' },
  { p:'Gigante', t:'adjetivo', d:'Mucho más grande de lo normal.', e:'Ese árbol es gigante comparado con los demás.' },
  { p:'Girasol', t:'sustantivo', d:'Planta con una flor grande y amarilla que gira siguiendo al sol.', e:'El girasol mira siempre hacia el sol.' },
  { p:'Glaciar', t:'sustantivo', d:'Gran masa de hielo que se mueve lentamente, formada por nieve acumulada durante muchos años.', e:'Los glaciares de la Patagonia son enormes.' },
  { p:'Globo', t:'sustantivo', d:'Bolsa de goma que se infla con aire o gas y flota o se usa para decorar.', e:'Los globos de colores adornaban la fiesta.' },
  { p:'Gorila', t:'sustantivo', d:'Primate grande y fuerte que vive en selvas de África.', e:'El gorila se golpeó el pecho.' },
  { p:'Gracias', t:'expresión', d:'Palabra que se usa para agradecer algo a alguien.', e:'Muchas gracias por tu ayuda.' },
  { p:'Granja', t:'sustantivo', d:'Terreno con animales y cultivos donde se producen alimentos.', e:'En la granja hay vacas, gallinas y ovejas.' },
  { p:'Guagua', t:'sustantivo', d:'Palabra chilena, de origen quechua, para referirse a un bebé.', e:'La guagua se quedó dormida en brazos de su mamá.' },
  { p:'Guitarra', t:'sustantivo', d:'Instrumento musical de cuerdas que se toca con los dedos o una púa.', e:'Mi hermano toca la guitarra todas las tardes.' },
  { p:'Habilidad', t:'sustantivo', d:'Capacidad para hacer algo bien.', e:'Tiene mucha habilidad para el dibujo.' },
  { p:'Hábito', t:'sustantivo', d:'Costumbre que se repite y se hace casi sin pensar.', e:'Lavarse los dientes es un buen hábito.' },
  { p:'Helado', t:'sustantivo', d:'Postre frío y dulce hecho de leche o agua con azúcar y sabores.', e:'En verano comemos helado casi todos los días.' },
  { p:'Hermano', t:'sustantivo', d:'Persona que tiene los mismos padres que otra.', e:'Mi hermano menor aprendió a andar en bicicleta.' },
  { p:'Herramienta', t:'sustantivo', d:'Instrumento que ayuda a realizar un trabajo.', e:'El martillo es una herramienta útil.' },
  { p:'Hielo', t:'sustantivo', d:'Agua congelada, sólida y fría.', e:'Puse hielo en el jugo para que estuviera frío.' },
  { p:'Himno', t:'sustantivo', d:'Canción solemne que representa a un país, institución o grupo.', e:'Cantamos el himno nacional en el acto.' },
  { p:'Historia', t:'sustantivo', d:'Relato de hechos; también, la ciencia que estudia el pasado de la humanidad.', e:'En historia aprendimos sobre los pueblos originarios.' },
  { p:'Hogar', t:'sustantivo', d:'Casa o lugar donde una persona vive y se siente segura y querida.', e:'No hay nada como volver al hogar.' },
  { p:'Honesto', t:'adjetivo', d:'Que dice la verdad y actúa de forma justa y correcta.', e:'Fue honesto y devolvió lo que encontró.' },
  { p:'Hormiga', t:'sustantivo', d:'Insecto pequeño y trabajador que vive en colonias organizadas.', e:'Las hormigas cargaban una hoja mucho más grande que ellas.' },
  { p:'Hospital', t:'sustantivo', d:'Lugar donde se atiende y trata a personas enfermas o heridas.', e:'Lo llevaron al hospital para revisarlo.' },
  { p:'Huaso', t:'sustantivo', d:'Hombre del campo chileno, experto jinete, que viste traje típico y participa en rodeos.', e:'El huaso arreó el ganado a caballo.' },
  { p:'Huella', t:'sustantivo', d:'Marca que deja el pie o una pata al pisar.', e:'Encontramos huellas de zorro en la nieve.' },
  { p:'Huerto', t:'sustantivo', d:'Terreno pequeño donde se cultivan verduras, frutas o hierbas.', e:'En el huerto del colegio plantamos lechugas.' },
  { p:'Huevo', t:'sustantivo', d:'Objeto ovalado que ponen las aves y otros animales, del que puede nacer una cría.', e:'Cociné dos huevos para el desayuno.' },
  { p:'Idea', t:'sustantivo', d:'Pensamiento que aparece en la mente sobre algo.', e:'Se me ocurrió una idea para el proyecto.' },
  { p:'Idioma', t:'sustantivo', d:'Lengua que habla un pueblo o país, como el español o el inglés.', e:'En Chile el idioma más hablado es el español.' },
  { p:'Iglú', t:'sustantivo', d:'Vivienda hecha de bloques de hielo o nieve, típica de zonas muy frías.', e:'Los inuit construyen iglús para protegerse del frío.' },
  { p:'Igualdad', t:'sustantivo', d:'Situación en que todas las personas tienen los mismos derechos y oportunidades.', e:'La escuela promueve la igualdad entre todos los estudiantes.' },
  { p:'Imaginar', t:'verbo', d:'Formar ideas o imágenes en la mente de cosas que no están presentes.', e:'Me gusta imaginar mundos de fantasía.' },
  { p:'Imán', t:'sustantivo', d:'Objeto que atrae metales como el hierro.', e:'El imán levantó los clavos de la mesa.' },
  { p:'Ingeniero', t:'sustantivo', d:'Persona que diseña y construye máquinas, edificios, puentes u otras obras.', e:'La ingeniera diseñó el nuevo puente.' },
  { p:'Insecto', t:'sustantivo', d:'Animal pequeño de seis patas, como la hormiga o la abeja.', e:'El insecto caminaba por la hoja.' },
  { p:'Inteligencia', t:'sustantivo', d:'Capacidad para entender, aprender y resolver problemas.', e:'Resolvió el acertijo gracias a su inteligencia.' },
  { p:'Internet', t:'sustantivo', d:'Red mundial que conecta computadores y permite compartir información.', e:'Buscamos la tarea en internet.' },
  { p:'Invento', t:'sustantivo', d:'Objeto o idea creada por primera vez para resolver un problema.', e:'La bombilla eléctrica fue un gran invento.' },
  { p:'Invierno', t:'sustantivo', d:'Estación más fría del año, entre el otoño y la primavera.', e:'En invierno llueve mucho en el sur.' },
  { p:'Isla', t:'sustantivo', d:'Porción de tierra rodeada de agua por todas partes.', e:'Chiloé es una isla grande de Chile.' },
  { p:'Jardín', t:'sustantivo', d:'Terreno donde se cultivan plantas y flores para adornar.', e:'El jardín está lleno de flores en primavera.' },
  { p:'Jaula', t:'sustantivo', d:'Estructura con barrotes que sirve para encerrar o transportar animales.', e:'El canario vivía en una jaula grande.' },
  { p:'Jirafa', t:'sustantivo', d:'Animal de cuello muy largo que vive en África y come hojas de los árboles.', e:'La jirafa alcanzó las hojas más altas.' },
  { p:'Joya', t:'sustantivo', d:'Objeto de valor, generalmente de metal o piedras preciosas, usado como adorno.', e:'Guardó sus joyas en una cajita.' },
  { p:'Juego', t:'sustantivo', d:'Actividad que se hace para divertirse, muchas veces con reglas.', e:'Mi juego favorito es la escondida.' },
  { p:'Jugo', t:'sustantivo', d:'Líquido que se obtiene de frutas u otros alimentos.', e:'Preparé jugo de naranja natural.' },
  { p:'Justo', t:'adjetivo', d:'Que actúa dando a cada uno lo que corresponde, sin favorecer a nadie.', e:'El árbitro fue justo con los dos equipos.' },
  { p:'Ladrillo', t:'sustantivo', d:'Bloque de barro cocido que se usa para construir paredes.', e:'La casa está hecha de ladrillo.' },
  { p:'Laguna', t:'sustantivo', d:'Extensión de agua más pequeña que un lago, generalmente de poca profundidad.', e:'Vimos flamencos en la laguna.' },
  { p:'Lámpara', t:'sustantivo', d:'Objeto que produce luz artificial.', e:'Encendió la lámpara del velador.' },
  { p:'Lana', t:'sustantivo', d:'Fibra suave que se obtiene del pelo de la oveja u otros animales.', e:'Tejió una bufanda de lana.' },
  { p:'Lápiz', t:'sustantivo', d:'Instrumento alargado que sirve para escribir o dibujar.', e:'Saqué punta a mi lápiz.' },
  { p:'Leche', t:'sustantivo', d:'Líquido blanco que producen las hembras de los mamíferos para alimentar a sus crías.', e:'Tomó un vaso de leche antes de dormir.' },
  { p:'Lechuza', t:'sustantivo', d:'Ave nocturna de ojos grandes que caza de noche.', e:'La lechuza vuela sin hacer ruido.' },
  { p:'Leer', t:'verbo', d:'Mirar y comprender lo que está escrito.', e:'Antes de dormir me gusta leer un cuento.' },
  { p:'Lengua', t:'sustantivo', d:'Órgano dentro de la boca que ayuda a hablar, saborear y tragar; también, el idioma que habla un pueblo.', e:'Sacó la lengua para que el doctor la revisara.' },
  { p:'León', t:'sustantivo', d:'Animal grande y fuerte, conocido como "el rey de la selva", que vive en grupos llamados manadas.', e:'El león rugió desde lo alto de la roca.' },
  { p:'Letra', t:'sustantivo', d:'Cada uno de los signos que forman el alfabeto.', e:'La primera letra de su nombre es una M.' },
  { p:'Ley', t:'sustantivo', d:'Norma que todos deben cumplir en un país, creada para vivir en orden y justicia.', e:'La ley protege los derechos de los niños.' },
  { p:'Libertad', t:'sustantivo', d:'Posibilidad de decidir y actuar por uno mismo, respetando a los demás.', e:'Los pájaros vuelan en libertad.' },
  { p:'Libro', t:'sustantivo', d:'Conjunto de hojas escritas, unidas y con tapas, que cuenta historias o entrega conocimientos.', e:'Terminé el libro en una semana.' },
  { p:'Limpio', t:'adjetivo', d:'Que no tiene suciedad ni manchas.', e:'Dejamos el patio limpio después de jugar.' },
  { p:'Linterna', t:'sustantivo', d:'Aparato portátil que produce luz, útil en la oscuridad.', e:'Usamos una linterna para explorar la cueva.' },
  { p:'Liviano', t:'adjetivo', d:'Que pesa poco.', e:'La pluma es muy liviana.' },
  { p:'Llave', t:'sustantivo', d:'Objeto de metal que sirve para abrir o cerrar una cerradura.', e:'Buscó la llave de la casa en su mochila.' },
  { p:'Lobo', t:'sustantivo', d:'Animal salvaje parecido a un perro grande, que vive y caza en manada.', e:'El lobo aulló bajo la luna llena.' },
  { p:'Lugar', t:'sustantivo', d:'Espacio o sitio determinado.', e:'Este es un buen lugar para acampar.' },
  { p:'Luna', t:'sustantivo', d:'Cuerpo del espacio que gira alrededor de la Tierra y brilla de noche reflejando la luz del sol.', e:'La luna llena iluminaba el patio.' },
  { p:'Madera', t:'sustantivo', d:'Material sólido que se obtiene del tronco de los árboles.', e:'La mesa está hecha de madera de roble.' },
  { p:'Maestro', t:'sustantivo', d:'Persona que enseña con experiencia y dedicación; sinónimo de profesor.', e:'El maestro de música toca varios instrumentos.' },
  { p:'Magia', t:'sustantivo', d:'Arte de hacer trucos que parecen imposibles; también, algo que parece encantador o mágico.', e:'El mago hizo un truco de magia asombroso.' },
  { p:'Mamífero', t:'sustantivo', d:'Animal que tiene pelo y alimenta a sus crías con leche.', e:'El ser humano es un mamífero.' },
  { p:'Mano', t:'sustantivo', d:'Parte del cuerpo al final del brazo, con dedos, que usamos para tomar cosas.', e:'Se lavó las manos antes de comer.' },
  { p:'Mapa', t:'sustantivo', d:'Dibujo que representa un territorio, como un país o una ciudad, visto desde arriba.', e:'Ubicamos Chile en el mapa.' },
  { p:'Mar', t:'sustantivo', d:'Gran masa de agua salada que cubre parte de la Tierra.', e:'En verano vamos a la playa a ver el mar.' },
  { p:'Marioneta', t:'sustantivo', d:'Muñeco que se mueve mediante hilos o con la mano, usado en teatro.', e:'El titiritero movía la marioneta con hilos.' },
  { p:'Mariposa', t:'sustantivo', d:'Insecto de alas grandes y colores llamativos que antes fue oruga.', e:'Una mariposa se posó en la flor.' },
  { p:'Medianoche', t:'sustantivo', d:'Las doce de la noche, el momento central de la noche.', e:'Los fuegos artificiales empezaron a medianoche.' },
  { p:'Médico', t:'sustantivo', d:'Persona que estudia y trata las enfermedades para cuidar la salud de las personas.', e:'El médico revisó mi garganta.' },
  { p:'Mediodía', t:'sustantivo', d:'Las doce del día.', e:'Almorzamos al mediodía.' },
  { p:'Medir', t:'verbo', d:'Averiguar el tamaño, la cantidad o la duración de algo.', e:'Vamos a medir el largo de la mesa.' },
  { p:'Mercado', t:'sustantivo', d:'Lugar donde se compran y venden productos.', e:'Compramos pescado fresco en el mercado.' },
  { p:'Miedo', t:'sustantivo', d:'Sensación de temor frente a un peligro real o imaginado.', e:'Sintió miedo durante la tormenta, pero se calmó rápido.' },
  { p:'Minuto', t:'sustantivo', d:'Unidad de tiempo que dura sesenta segundos.', e:'Espera solo un minuto, ya vuelvo.' },
  { p:'Mochila', t:'sustantivo', d:'Bolso con correas que se lleva en la espalda para transportar cosas.', e:'Guardó los cuadernos en su mochila.' },
  { p:'Momento', t:'sustantivo', d:'Espacio breve de tiempo.', e:'Espera un momento, ya termino.' },
  { p:'Moneda', t:'sustantivo', d:'Pieza de metal que se usa como dinero.', e:'Encontró una moneda antigua en el jardín.' },
  { p:'Montaña', t:'sustantivo', d:'Elevación natural y grande del terreno.', e:'Subimos la montaña en dos horas.' },
  { p:'Muralla', t:'sustantivo', d:'Muro grueso y alto, generalmente construido para defender un lugar.', e:'La Gran Muralla China se ve incluso desde lejos.' },
  { p:'Museo', t:'sustantivo', d:'Lugar donde se exhiben y conservan obras de arte, objetos históricos o científicos.', e:'Vimos dinosaurios en el museo de historia natural.' },
  { p:'Música', t:'sustantivo', d:'Arte de combinar sonidos de forma agradable o expresiva.', e:'La música de esa canción me alegra.' },
  { p:'Nariz', t:'sustantivo', d:'Parte de la cara que sirve para respirar y oler.', e:'El perro usa su nariz para encontrar comida.' },
  { p:'Natación', t:'sustantivo', d:'Deporte que consiste en nadar, generalmente en una piscina o el mar.', e:'Practica natación dos veces por semana.' },
  { p:'Naturaleza', t:'sustantivo', d:'Todo lo que existe sin que lo haya hecho el ser humano: plantas, animales, ríos, montañas.', e:'Debemos cuidar la naturaleza.' },
  { p:'Neblina', t:'sustantivo', d:'Niebla poco densa que dificulta ver a lo lejos.', e:'La neblina cubrió el cerro en la mañana.' },
  { p:'Nieve', t:'sustantivo', d:'Agua congelada que cae del cielo en copos blancos cuando hace mucho frío.', e:'Los niños jugaron con la nieve recién caída.' },
  { p:'Noticia', t:'sustantivo', d:'Información sobre algo que acaba de ocurrir.', e:'Escuchamos la noticia en la radio.' },
  { p:'Nube', t:'sustantivo', d:'Conjunto de gotitas de agua que flota en el cielo.', e:'Esa nube parece un conejo.' },
  { p:'Número', t:'sustantivo', d:'Símbolo que sirve para contar, medir y ordenar.', e:'El número siete es mi favorito.' },
  { p:'Nutritivo', t:'adjetivo', d:'Que aporta buenos nutrientes al cuerpo.', e:'La quinoa es un alimento muy nutritivo.' },
  { p:'Océano', t:'sustantivo', d:'Extensión enorme de agua salada, más grande que un mar. Chile mira al océano Pacífico.', e:'El océano Pacífico es el más grande del mundo.' },
  { p:'Ola', t:'sustantivo', d:'Movimiento del agua del mar que se eleva y rompe en la orilla.', e:'Las olas eran perfectas para surfear.' },
  { p:'Oreja', t:'sustantivo', d:'Parte externa del cuerpo que permite escuchar.', e:'El conejo tiene las orejas muy largas.' },
  { p:'Orgullo', t:'sustantivo', d:'Satisfacción que se siente por un logro propio o de alguien querido.', e:'Sintió orgullo al terminar su proyecto.' },
  { p:'Orquesta', t:'sustantivo', d:'Grupo grande de músicos que tocan instrumentos juntos.', e:'La orquesta tocó una sinfonía completa.' },
  { p:'Oso', t:'sustantivo', d:'Animal grande y peludo, de patas fuertes, que puede trepar árboles.', e:'El oso pescó un salmón en el río.' },
  { p:'Otoño', t:'sustantivo', d:'Estación del año en que las hojas de muchos árboles cambian de color y caen.', e:'En otoño el parque se llena de hojas secas.' },
  { p:'Oveja', t:'sustantivo', d:'Animal de granja cubierto de lana, del que se obtiene lana y a veces leche.', e:'La oveja fue esquilada en primavera.' },
  { p:'Paciencia', t:'sustantivo', d:'Capacidad de esperar o perseverar con calma, sin enojarse.', e:'Armar el rompecabezas requiere paciencia.' },
  { p:'Paisaje', t:'sustantivo', d:'Extensión de terreno que se ve desde un lugar, con sus elementos naturales o construidos.', e:'El paisaje del lago era precioso.' },
  { p:'Palabra', t:'sustantivo', d:'Sonido o conjunto de letras que expresa una idea.', e:'Aprendí una palabra nueva hoy.' },
  { p:'Paloma', t:'sustantivo', d:'Ave gris o blanca, común en las ciudades, símbolo de la paz.', e:'Las palomas comían migas de pan en la plaza.' },
  { p:'Pan', t:'sustantivo', d:'Alimento hecho con harina, agua y levadura, horneado. En Chile es típica la marraqueta.', e:'Compramos pan fresco en la tarde.' },
  { p:'Papá', t:'sustantivo', d:'Padre, en lenguaje cariñoso o familiar.', e:'Mi papá me enseñó a andar en bicicleta.' },
  { p:'Paraguas', t:'sustantivo', d:'Objeto que se abre para protegerse de la lluvia.', e:'Abrió el paraguas cuando empezó a llover.' },
  { p:'Pared', t:'sustantivo', d:'Construcción vertical que separa espacios o sostiene un techo.', e:'Colgó un cuadro en la pared.' },
  { p:'Pariente', t:'sustantivo', d:'Persona de la misma familia.', e:'Vinieron parientes de todo el país al matrimonio.' },
  { p:'Pastel', t:'sustantivo', d:'Preparación dulce horneada, generalmente hecha con harina, huevos y azúcar.', e:'Hicimos un pastel de cumpleaños de chocolate.' },
  { p:'Patria', t:'sustantivo', d:'País al que una persona pertenece y siente como propio.', e:'Cantamos con orgullo por nuestra patria.' },
  { p:'Paz', t:'sustantivo', d:'Estado de tranquilidad, sin guerra ni conflictos.', e:'Los países firmaron un acuerdo de paz.' },
  { p:'Pelota', t:'sustantivo', d:'Objeto redondo que se usa para jugar, botar o lanzar.', e:'Jugamos a patear la pelota en el patio.' },
  { p:'Pescado', t:'sustantivo', d:'Animal acuático que se pesca para comer.', e:'Comimos pescado frito el viernes.' },
  { p:'Pescador', t:'sustantivo', d:'Persona que se dedica a pescar.', e:'El pescador salió al mar antes del amanecer.' },
  { p:'Piano', t:'sustantivo', d:'Instrumento musical de teclas que produce sonido al golpear cuerdas internas.', e:'Aprendió a tocar el piano este año.' },
  { p:'Piedra', t:'sustantivo', d:'Trozo sólido y duro de roca.', e:'Tropezó con una piedra en el camino.' },
  { p:'Pingüino', t:'sustantivo', d:'Ave que no vuela pero nada muy bien, y vive en climas fríos.', e:'El pingüino se deslizó sobre el hielo.' },
  { p:'Piscina', t:'sustantivo', d:'Estanque construido para nadar o bañarse.', e:'Nadamos en la piscina todo el verano.' },
  { p:'Planeta', t:'sustantivo', d:'Cuerpo del espacio que gira alrededor de una estrella. La Tierra es un planeta.', e:'Marte es conocido como el planeta rojo.' },
  { p:'Planta', t:'sustantivo', d:'Ser vivo que generalmente crece fijo en la tierra y fabrica su alimento con la luz del sol.', e:'Riego mi planta dos veces por semana.' },
  { p:'Playa', t:'sustantivo', d:'Terreno de arena junto al mar, un río o un lago.', e:'Construimos castillos en la playa.' },
  { p:'Plaza', t:'sustantivo', d:'Espacio público y abierto dentro de una ciudad o pueblo.', e:'Los niños juegan en la plaza los fines de semana.' },
  { p:'Poesía', t:'sustantivo', d:'Forma de expresión artística que usa el lenguaje con ritmo y belleza, en versos.', e:'Escribió una poesía sobre el mar.' },
  { p:'Policía', t:'sustantivo', d:'Persona encargada de cuidar el orden y la seguridad de las personas.', e:'La policía ayudó a cruzar la calle a los niños.' },
  { p:'Pregunta', t:'sustantivo', d:'Frase con la que se pide información sobre algo.', e:'Hice una pregunta en clases y la profesora la respondió.' },
  { p:'Primavera', t:'sustantivo', d:'Estación del año en que florecen las plantas, entre el invierno y el verano.', e:'En primavera el jardín se llena de flores.' },
  { p:'Prisa', t:'sustantivo', d:'Necesidad o deseo de hacer algo rápido.', e:'Tenía prisa porque se le hacía tarde.' },
  { p:'Profesor', t:'sustantivo', d:'Persona que enseña a otras en un colegio, universidad u otro lugar.', e:'El profesor explicó la materia con ejemplos.' },
  { p:'Puente', t:'sustantivo', d:'Construcción que permite cruzar un río, camino u otro obstáculo.', e:'Cruzamos el puente para llegar al otro lado.' },
  { p:'Puerta', t:'sustantivo', d:'Abertura en una pared que se abre y cierra para entrar o salir de un lugar.', e:'Cerró la puerta con cuidado.' },
  { p:'Puerto', t:'sustantivo', d:'Lugar de la costa donde los barcos cargan y descargan personas o mercancías.', e:'Valparaíso es un puerto muy importante de Chile.' },
  { p:'Pug', t:'sustantivo', d:'Raza de perro pequeño, de cara arrugada, hocico corto y carácter cariñoso. ¡Como Carboncito!', e:'El pug corrió feliz a saludar.' },
  { p:'Puma', t:'sustantivo', d:'Felino grande de Chile, de color café claro, también llamado león de montaña.', e:'El puma vive en la cordillera de los Andes.' },
  { p:'Quena', t:'sustantivo', d:'Instrumento de viento andino, hecho de caña, parecido a una flauta.', e:'El músico tocaba la quena en la plaza.' },
  { p:'Queso', t:'sustantivo', d:'Alimento sólido hecho de leche cuajada.', e:'El sándwich lleva jamón y queso.' },
  { p:'Rana', t:'sustantivo', d:'Animal anfibio de piel húmeda que salta y vive cerca del agua.', e:'La rana saltó al estanque.' },
  { p:'Rápido', t:'adjetivo', d:'Que se mueve o hace algo en poco tiempo.', e:'El guepardo es el animal terrestre más rápido.' },
  { p:'Ratón', t:'sustantivo', d:'Animal pequeño de cola larga; también, dispositivo que mueve el cursor del computador.', e:'El ratón se escondió detrás del mueble.' },
  { p:'Receta', t:'sustantivo', d:'Instrucciones que explican cómo preparar una comida; también, indicación médica para comprar un medicamento.', e:'Seguimos la receta para hacer el pastel.' },
  { p:'Reciclar', t:'verbo', d:'Transformar materiales usados, como el papel o el plástico, para volver a usarlos.', e:'Aprendimos a reciclar botellas y cartón.' },
  { p:'Recreo', t:'sustantivo', d:'Tiempo libre entre clases para descansar y jugar.', e:'En el recreo jugamos a la pinta.' },
  { p:'Regalo', t:'sustantivo', d:'Objeto que se da a alguien para alegrarlo, sin esperar nada a cambio.', e:'Le hicieron un regalo por su cumpleaños.' },
  { p:'Regla', t:'sustantivo', d:'Instrumento plano con medidas que sirve para medir y trazar líneas rectas.', e:'Usé la regla para dibujar el margen.' },
  { p:'Reloj', t:'sustantivo', d:'Instrumento que sirve para saber la hora.', e:'El reloj de la sala marca las tres.' },
  { p:'Reptil', t:'sustantivo', d:'Animal de piel escamosa que no regula su temperatura interna, como la serpiente o la lagartija.', e:'La lagartija es un reptil pequeño.' },
  { p:'Respeto', t:'sustantivo', d:'Consideración y buen trato hacia las personas, los seres vivos y las cosas.', e:'Tratamos con respeto a todos los compañeros.' },
  { p:'Rey', t:'sustantivo', d:'Hombre que gobierna un reino, generalmente heredando el cargo de su familia.', e:'El rey vivía en un enorme palacio.' },
  { p:'Río', t:'sustantivo', d:'Corriente natural de agua dulce que fluye hacia el mar, un lago u otro río.', e:'El río Biobío es uno de los más anchos de Chile.' },
  { p:'Risa', t:'sustantivo', d:'Sonido y gesto que hacemos cuando algo nos parece divertido.', e:'Su chiste nos sacó una risa a todos.' },
  { p:'Robot', t:'sustantivo', d:'Máquina programada para realizar tareas de forma automática.', e:'El robot armó las piezas solo.' },
  { p:'Rueda', t:'sustantivo', d:'Objeto redondo que gira y permite el movimiento de vehículos.', e:'Cambiamos la rueda pinchada del auto.' },
  { p:'Sabor', t:'sustantivo', d:'Sensación que produce un alimento en la boca.', e:'El helado tenía sabor a frutilla.' },
  { p:'Sabroso', t:'adjetivo', d:'Que tiene buen sabor.', e:'El pastel quedó muy sabroso.' },
  { p:'Salar', t:'sustantivo', d:'Terreno cubierto de una capa de sal, común en el norte de Chile.', e:'El Salar de Atacama tiene flamencos rosados.' },
  { p:'Salud', t:'sustantivo', d:'Estado de bienestar físico y mental de una persona.', e:'Comer sano ayuda a mantener la salud.' },
  { p:'Saludable', t:'adjetivo', d:'Que hace bien a la salud.', e:'La fruta es una colación saludable.' },
  { p:'Satélite', t:'sustantivo', d:'Objeto que gira alrededor de un planeta; puede ser natural, como la Luna, o artificial, hecho por el ser humano.', e:'El satélite envía señales de televisión.' },
  { p:'Segundo', t:'sustantivo', d:'Unidad de tiempo muy breve; sesenta segundos forman un minuto.', e:'Corrió los cien metros en pocos segundos.' },
  { p:'Selva', t:'sustantivo', d:'Bosque tropical con muchísimos árboles, plantas y animales, y clima cálido y húmedo.', e:'La selva amazónica tiene una enorme variedad de especies.' },
  { p:'Semáforo', t:'sustantivo', d:'Aparato con luces rojas, amarillas y verdes que regula el tránsito.', e:'Esperamos a que el semáforo se pusiera verde.' },
  { p:'Semana', t:'sustantivo', d:'Período de siete días.', e:'La semana empieza el lunes.' },
  { p:'Semilla', t:'sustantivo', d:'Parte de una planta de la que puede nacer una planta nueva.', e:'Plantamos una semilla de zapallo.' },
  { p:'Serpiente', t:'sustantivo', d:'Animal reptil de cuerpo alargado, sin patas, que se desliza por el suelo.', e:'La serpiente se deslizó entre las piedras.' },
  { p:'Silla', t:'sustantivo', d:'Mueble con respaldo que sirve para sentarse.', e:'Acercó una silla a la mesa.' },
  { p:'Sol', t:'sustantivo', d:'Estrella que da luz y calor a la Tierra.', e:'El sol sale por el este cada mañana.' },
  { p:'Sombra', t:'sustantivo', d:'Zona oscura que se forma cuando algo bloquea la luz.', e:'Nos sentamos bajo la sombra del árbol.' },
  { p:'Soñar', t:'verbo', d:'Imaginar historias mientras dormimos; también, desear algo con ilusión.', e:'Sueña con ser astrónoma.' },
  { p:'Sonrisa', t:'sustantivo', d:'Gesto alegre que se hace curvando los labios, sin llegar a reír.', e:'Me recibió con una gran sonrisa.' },
  { p:'Sopa', t:'sustantivo', d:'Comida líquida hecha con caldo y otros ingredientes.', e:'La sopa de verduras estaba calentita.' },
  { p:'Sorpresa', t:'sustantivo', d:'Sentimiento que se produce cuando ocurre algo inesperado.', e:'Le organizaron una fiesta sorpresa.' },
  { p:'Suave', t:'adjetivo', d:'Que es agradable al tacto, sin asperezas.', e:'La lana de la alpaca es muy suave.' },
  { p:'Talento', t:'sustantivo', d:'Habilidad natural para hacer algo muy bien.', e:'Tiene un gran talento para el dibujo.' },
  { p:'Tambor', t:'sustantivo', d:'Instrumento musical de percusión, formado por un cuerpo hueco cubierto con una membrana que se golpea.', e:'El tambor marcó el ritmo del desfile.' },
  { p:'Techo', t:'sustantivo', d:'Parte superior de una construcción que la cubre.', e:'La lluvia repiqueteaba en el techo.' },
  { p:'Teléfono', t:'sustantivo', d:'Aparato que permite hablar o comunicarse con personas que están lejos.', e:'La llamó por teléfono para saludarla.' },
  { p:'Tesoro', t:'sustantivo', d:'Conjunto de objetos valiosos, muchas veces escondido.', e:'Los piratas buscaban un tesoro enterrado.' },
  { p:'Tiempo', t:'sustantivo', d:'Duración de las cosas; también se usa para hablar del clima.', e:'Nos quedó poco tiempo para terminar.' },
  { p:'Tierra', t:'sustantivo', d:'Planeta donde vivimos; también, el suelo donde crecen las plantas.', e:'La Tierra gira alrededor del Sol.' },
  { p:'Tigre', t:'sustantivo', d:'Felino grande de rayas negras y anaranjadas, que vive en Asia.', e:'El tigre nadó a través del río.' },
  { p:'Tijeras', t:'sustantivo', d:'Herramienta con dos hojas filosas que sirve para cortar papel u otros materiales.', e:'Recorté la figura con tijeras.' },
  { p:'Timbre', t:'sustantivo', d:'Aparato que suena para avisar o llamar.', e:'Tocó el timbre de la casa.' },
  { p:'Tortuga', t:'sustantivo', d:'Animal de caparazón duro que se mueve lentamente y puede vivir muchos años.', e:'La tortuga escondió la cabeza en su caparazón.' },
  { p:'Trabajo', t:'sustantivo', d:'Actividad que se realiza con esfuerzo para lograr o producir algo.', e:'El trabajo en equipo salió muy bien.' },
  { p:'Tren', t:'sustantivo', d:'Medio de transporte formado por vagones que avanzan sobre rieles.', e:'El tren llegó puntual a la estación.' },
  { p:'Trineo', t:'sustantivo', d:'Vehículo sin ruedas que se desliza sobre nieve o hielo.', e:'Bajaron la colina en un trineo.' },
  { p:'Triste', t:'adjetivo', d:'Que siente pena o tristeza.', e:'Se puso triste porque perdió su juguete.' },
  { p:'Túnel', t:'sustantivo', d:'Paso subterráneo construido para atravesar una montaña u otro obstáculo.', e:'El tren pasó por un largo túnel.' },
  { p:'Universo', t:'sustantivo', d:'Todo lo que existe: los planetas, las estrellas, las galaxias y el espacio.', e:'El universo es inmenso y sigue expandiéndose.' },
  { p:'Útil', t:'adjetivo', d:'Que sirve para algo o ayuda a lograr un fin.', e:'Esa mochila es muy útil para el colegio.' },
  { p:'Uva', t:'sustantivo', d:'Fruta pequeña y redonda que crece en racimos, usada para hacer vino y jugo.', e:'Comimos un racimo de uvas verdes.' },
  { p:'Vaca', t:'sustantivo', d:'Animal de granja que da leche y se cría también por su carne.', e:'La vaca pastaba tranquila en el potrero.' },
  { p:'Valiente', t:'adjetivo', d:'Que enfrenta el miedo o las dificultades con decisión.', e:'Fue valiente y contó la verdad.' },
  { p:'Valle', t:'sustantivo', d:'Terreno llano entre montañas, por donde a veces pasa un río.', e:'El valle central de Chile es muy fértil.' },
  { p:'Vecino', t:'sustantivo', d:'Persona que vive cerca de otra, en la misma calle o edificio.', e:'Saludamos a nuestro vecino todas las mañanas.' },
  { p:'Vela', t:'sustantivo', d:'Barra de cera con una mecha que arde y da luz; también, la tela de un barco que lo impulsa con el viento.', e:'Sopló las velas de su torta de cumpleaños.' },
  { p:'Ventana', t:'sustantivo', d:'Abertura en una pared, con vidrio, que deja entrar luz y aire.', e:'Desde la ventana se ve la cordillera.' },
  { p:'Verano', t:'sustantivo', d:'Estación más calurosa del año, entre la primavera y el otoño.', e:'En verano vamos a la piscina.' },
  { p:'Verdad', t:'sustantivo', d:'Lo que corresponde a la realidad de los hechos.', e:'Decir la verdad genera confianza.' },
  { p:'Verdura', t:'sustantivo', d:'Planta comestible, generalmente de hoja o raíz, como la lechuga o la zanahoria.', e:'Comimos verduras frescas en el almuerzo.' },
  { p:'Veterinario', t:'sustantivo', d:'Persona que cuida la salud de los animales.', e:'El veterinario revisó a mi perro.' },
  { p:'Vestido', t:'sustantivo', d:'Prenda de ropa femenina de una sola pieza.', e:'Se puso un vestido azul para la fiesta.' },
  { p:'Viajar', t:'verbo', d:'Trasladarse de un lugar a otro, generalmente lejano.', e:'Queremos viajar al norte en las vacaciones.' },
  { p:'Vidrio', t:'sustantivo', d:'Material duro y transparente hecho con arena fundida.', e:'La ventana tiene un vidrio muy limpio.' },
  { p:'Violín', t:'sustantivo', d:'Instrumento musical de cuerdas que se toca con un arco.', e:'Tocó una melodía suave en el violín.' },
  { p:'Volcán', t:'sustantivo', d:'Montaña con una abertura por donde puede salir lava, ceniza y gases desde el interior de la Tierra.', e:'El volcán Villarrica está en el sur de Chile.' },
  { p:'Vuelo', t:'sustantivo', d:'Acción de volar, o el viaje que hace un avión de un lugar a otro.', e:'El vuelo a Isla de Pascua dura varias horas.' },
  { p:'Zanahoria', t:'sustantivo', d:'Verdura alargada de color naranjo que crece bajo la tierra.', e:'La ensalada lleva zanahoria rallada.' },
  { p:'Zapallo', t:'sustantivo', d:'Verdura grande de cáscara dura y pulpa anaranjada, muy usada en la cocina chilena.', e:'La sopa llevaba zapallo y choclo.' },
  { p:'Zapato', t:'sustantivo', d:'Prenda que cubre y protege el pie para caminar.', e:'Se amarró los cordones del zapato.' },
  { p:'Zorro', t:'sustantivo', d:'Animal salvaje parecido a un perro, de hocico puntiagudo y cola larga. El zorro culpeo vive en Chile.', e:'El zorro se escondió entre los arbustos.' },
];

const DICC_EN = [
  { w:'Actor', tr:'actor', e:'The actor performed on a big stage.' },
  { w:'Add', tr:'sumar', e:'Add these two numbers together.' },
  { w:'Adventure', tr:'aventura', e:'We went on an adventure in the forest.' },
  { w:'Afternoon', tr:'tarde', e:'We play soccer in the afternoon.' },
  { w:'Airplane', tr:'avión', e:'The airplane flies above the clouds.' },
  { w:'Airport', tr:'aeropuerto', e:'We waited for the plane at the airport.' },
  { w:'Alone', tr:'solo', e:'The cat likes to sleep alone.' },
  { w:'Always', tr:'siempre', e:'She always says thank you.' },
  { w:'Angry', tr:'enojado', e:'He was angry about the broken toy.' },
  { w:'Animal', tr:'animal', e:'The zoo has many kinds of animals.' },
  { w:'Ankle', tr:'tobillo', e:'She hurt her ankle playing soccer.' },
  { w:'Answer', tr:'respuesta', e:'I know the answer to that question.' },
  { w:'Ant', tr:'hormiga', e:'The ant carries food to its nest.' },
  { w:'Apple', tr:'manzana', e:'The apple is red and sweet.' },
  { w:'Arm', tr:'brazo', e:'He raised his arm to answer.' },
  { w:'Arrive', tr:'llegar', e:'We arrive at school at eight.' },
  { w:'Art', tr:'arte', e:'We paint in art class.' },
  { w:'Astronaut', tr:'astronauta', e:'The astronaut floated inside the spaceship.' },
  { w:'Aunt', tr:'tía', e:'My aunt lives in the south.' },
  { w:'Autumn', tr:'otoño', e:'Leaves fall in autumn.' },
  { w:'Baby', tr:'bebé', e:'The baby sleeps in the crib.' },
  { w:'Backpack', tr:'mochila', e:'My backpack is full of books.' },
  { w:'Bake', tr:'hornear', e:'We bake cookies on Sundays.' },
  { w:'Balloon', tr:'globo', e:'The balloon flew away into the sky.' },
  { w:'Basket', tr:'canasto', e:'She put the apples in a basket.' },
  { w:'Bathroom', tr:'baño', e:'Wash your hands in the bathroom.' },
  { w:'Beach', tr:'playa', e:'We play on the beach in summer.' },
  { w:'Beautiful', tr:'hermoso', e:'The sunset was beautiful.' },
  { w:'Bear', tr:'oso', e:'The bear caught a fish in the river.' },
  { w:'Bed', tr:'cama', e:'I make my bed every morning.' },
  { w:'Bee', tr:'abeja', e:'The bee makes honey.' },
  { w:'Begin', tr:'comenzar', e:'The movie will begin soon.' },
  { w:'Believe', tr:'creer', e:'I believe you can do it.' },
  { w:'Belt', tr:'cinturón', e:'He wore a brown belt.' },
  { w:'Bench', tr:'banco', e:'We sat on a bench in the park.' },
  { w:'Bicycle', tr:'bicicleta', e:'I ride my bicycle to the park.' },
  { w:'Big', tr:'grande', e:'The elephant is a big animal.' },
  { w:'Bird', tr:'pájaro', e:'The bird sings in the morning.' },
  { w:'Black', tr:'negro', e:'Carboncito is a black pug.' },
  { w:'Blanket', tr:'manta', e:'She covered up with a warm blanket.' },
  { w:'Blue', tr:'azul', e:'The sky is blue today.' },
  { w:'Body', tr:'cuerpo', e:'We learn about the human body at school.' },
  { w:'Bone', tr:'hueso', e:'The dog buried its bone.' },
  { w:'Book', tr:'libro', e:'This book has many pictures.' },
  { w:'Border', tr:'frontera', e:'The two countries share a border.' },
  { w:'Bottle', tr:'botella', e:'Fill the bottle with water.' },
  { w:'Box', tr:'caja', e:'We packed the toys in a box.' },
  { w:'Branch', tr:'rama', e:'A bird landed on the branch.' },
  { w:'Brave', tr:'valiente', e:'The firefighter was very brave.' },
  { w:'Bread', tr:'pan', e:'We eat bread at breakfast.' },
  { w:'Break', tr:'romper', e:'Be careful not to break the vase.' },
  { w:'Breakfast', tr:'desayuno', e:'I eat cereal for breakfast.' },
  { w:'Bridge', tr:'puente', e:'We crossed the bridge over the river.' },
  { w:'Bright', tr:'brillante', e:'The stars are bright tonight.' },
  { w:'Brother', tr:'hermano', e:'My brother plays the guitar.' },
  { w:'Bubble', tr:'burbuja', e:'The children blew soap bubbles.' },
  { w:'Build', tr:'construir', e:'They build sandcastles at the beach.' },
  { w:'Bus', tr:'bus', e:'We take the bus to school.' },
  { w:'Butterfly', tr:'mariposa', e:'The butterfly landed on the flower.' },
  { w:'Calendar', tr:'calendario', e:'We mark birthdays on the calendar.' },
  { w:'Calm', tr:'tranquilo', e:'The lake was calm and quiet.' },
  { w:'Camera', tr:'cámara', e:'He took a photo with his camera.' },
  { w:'Camp', tr:'campamento', e:'We went to summer camp.' },
  { w:'Candle', tr:'vela', e:'She blew out the candles on her cake.' },
  { w:'Candy', tr:'dulce', e:'She shared her candy with her friends.' },
  { w:'Cap', tr:'gorro', e:'He wore a cap to block the sun.' },
  { w:'Captain', tr:'capitán', e:'The captain steered the ship.' },
  { w:'Careful', tr:'cuidadoso', e:'Be careful with the scissors.' },
  { w:'Carrot', tr:'zanahoria', e:'Rabbits love to eat carrots.' },
  { w:'Carry', tr:'cargar', e:'Can you help me carry this box?' },
  { w:'Castle', tr:'castillo', e:'The castle had tall towers.' },
  { w:'Cat', tr:'gato', e:'The cat sleeps on the sofa.' },
  { w:'Cave', tr:'cueva', e:'Bats live inside the cave.' },
  { w:'Ceiling', tr:'techo', e:'A lamp hung from the ceiling.' },
  { w:'Celebrate', tr:'celebrar', e:'We celebrate her birthday every year.' },
  { w:'Center', tr:'centro', e:'Stand in the center of the room.' },
  { w:'Chair', tr:'silla', e:'Please sit on the chair.' },
  { w:'Chase', tr:'perseguir', e:'The dog likes to chase the ball.' },
  { w:'Cheap', tr:'barato', e:'This toy was very cheap.' },
  { w:'Cheese', tr:'queso', e:'The sandwich has ham and cheese.' },
  { w:'Chicken', tr:'pollo', e:'The chicken laid three eggs.' },
  { w:'Chocolate', tr:'chocolate', e:'She loves hot chocolate in winter.' },
  { w:'Choose', tr:'elegir', e:'You can choose any color you like.' },
  { w:'Circle', tr:'círculo', e:'Draw a circle around the correct answer.' },
  { w:'City', tr:'ciudad', e:'The city has tall buildings.' },
  { w:'Class', tr:'clase', e:'Our class has twenty students.' },
  { w:'Classroom', tr:'sala de clases', e:'We learn math in the classroom.' },
  { w:'Clean', tr:'limpio', e:'Keep your room clean.' },
  { w:'Climb', tr:'escalar', e:'They climb the hill every morning.' },
  { w:'Clock', tr:'reloj', e:"The clock shows three o'clock." },
  { w:'Cloud', tr:'nube', e:'That cloud looks like a rabbit.' },
  { w:'Coast', tr:'costa', e:'Many cities are near the coast.' },
  { w:'Coin', tr:'moneda', e:'He found an old coin in the garden.' },
  { w:'Cold', tr:'frío', e:'The water is very cold.' },
  { w:'Collect', tr:'coleccionar', e:'I collect stickers from every trip.' },
  { w:'Color', tr:'color', e:'What is your favorite color?' },
  { w:'Comfortable', tr:'cómodo', e:'This chair is very comfortable.' },
  { w:'Cook', tr:'cocinar', e:'My father likes to cook on weekends.' },
  { w:'Corner', tr:'esquina', e:'The store is on the corner.' },
  { w:'Count', tr:'contar', e:'Let’s count the stars we can see.' },
  { w:'Country', tr:'país', e:'Chile is a long, narrow country.' },
  { w:'Cousin', tr:'primo', e:'My cousin visits us every summer.' },
  { w:'Cow', tr:'vaca', e:'The cow gives us milk.' },
  { w:'Create', tr:'crear', e:'She likes to create her own stories.' },
  { w:'Crowd', tr:'multitud', e:'A big crowd watched the parade.' },
  { w:'Cry', tr:'llorar', e:'The baby began to cry.' },
  { w:'Cup', tr:'taza', e:'He drank tea from a small cup.' },
  { w:'Curious', tr:'curioso', e:'The curious cat looked inside the box.' },
  { w:'Dad', tr:'papá', e:'My dad tells the best jokes.' },
  { w:'Dance', tr:'bailar', e:'They dance at the party.' },
  { w:'Dangerous', tr:'peligroso', e:'Swimming there is dangerous.' },
  { w:'Dark', tr:'oscuro', e:'It gets dark early in winter.' },
  { w:'Daughter', tr:'hija', e:'Their daughter loves to paint.' },
  { w:'Decide', tr:'decidir', e:'We need to decide where to go.' },
  { w:'Deep', tr:'profundo', e:'The lake is very deep.' },
  { w:'Delicious', tr:'delicioso', e:'The soup was delicious.' },
  { w:'Dentist', tr:'dentista', e:'I visit the dentist twice a year.' },
  { w:'Describe', tr:'describir', e:'Can you describe your dream?' },
  { w:'Desert', tr:'desierto', e:'The Atacama Desert is very dry.' },
  { w:'Desk', tr:'escritorio', e:'She keeps her books on the desk.' },
  { w:'Dictionary', tr:'diccionario', e:'I look up new words in the dictionary.' },
  { w:'Different', tr:'diferente', e:'Every snowflake is different.' },
  { w:'Difficult', tr:'difícil', e:'That exam was very difficult.' },
  { w:'Discover', tr:'descubrir', e:'Scientists discover new species every year.' },
  { w:'Doctor', tr:'doctor', e:'The doctor listened to my heart.' },
  { w:'Dog', tr:'perro', e:'The dog runs in the park.' },
  { w:'Doll', tr:'muñeca', e:'She plays with her favorite doll.' },
  { w:'Dolphin', tr:'delfín', e:'The dolphin jumped out of the water.' },
  { w:'Door', tr:'puerta', e:'Please close the door.' },
  { w:'Dozen', tr:'docena', e:'We bought a dozen eggs.' },
  { w:'Draw', tr:'dibujar', e:'I like to draw animals.' },
  { w:'Dream', tr:'soñar', e:'Last night I had a good dream.' },
  { w:'Drink', tr:'beber', e:'I drink water every day.' },
  { w:'Drum', tr:'tambor', e:'He plays the drum in the band.' },
  { w:'Dry', tr:'seco', e:'The desert is very dry.' },
  { w:'Duck', tr:'pato', e:'The duck swims in the pond.' },
  { w:'Ear', tr:'oreja', e:'Rabbits have very long ears.' },
  { w:'Earth', tr:'Tierra', e:'The Earth orbits the Sun.' },
  { w:'Easy', tr:'fácil', e:'This puzzle is easy for me.' },
  { w:'Eat', tr:'comer', e:'We eat lunch at school.' },
  { w:'Egg', tr:'huevo', e:'I had a boiled egg for breakfast.' },
  { w:'Elbow', tr:'codo', e:'He bent his elbow to wave.' },
  { w:'Elephant', tr:'elefante', e:'The elephant has a long trunk.' },
  { w:'Empty', tr:'vacío', e:'The glass is empty now.' },
  { w:'End', tr:'final', e:'We reached the end of the trail.' },
  { w:'Enjoy', tr:'disfrutar', e:'We enjoy playing outside.' },
  { w:'Enter', tr:'entrar', e:'Please enter through the main door.' },
  { w:'Eraser', tr:'goma', e:'Can I borrow your eraser?' },
  { w:'Evening', tr:'tarde', e:'We watched the sunset in the evening.' },
  { w:'Everyone', tr:'todos', e:'Everyone clapped at the end of the show.' },
  { w:'Exam', tr:'examen', e:'She studied hard for the exam.' },
  { w:'Exercise', tr:'ejercicio', e:'Exercise keeps your body healthy.' },
  { w:'Expensive', tr:'caro', e:'That bicycle looks expensive.' },
  { w:'Explore', tr:'explorar', e:"Let's explore the forest." },
  { w:'Eye', tr:'ojo', e:'Close your eyes and make a wish.' },
  { w:'Face', tr:'cara', e:'She washed her face before bed.' },
  { w:'Factory', tr:'fábrica', e:'The factory makes toys and games.' },
  { w:'Fair', tr:'justo', e:'The referee was very fair.' },
  { w:'Fall', tr:'caer', e:'Be careful not to fall.' },
  { w:'Family', tr:'familia', e:'My family is very big.' },
  { w:'Farm', tr:'granja', e:'The farm has cows and chickens.' },
  { w:'Farmer', tr:'agricultor', e:'The farmer plants corn every spring.' },
  { w:'Fast', tr:'rápido', e:'The train is very fast.' },
  { w:'Father', tr:'padre', e:'My father cooks on Sundays.' },
  { w:'Feather', tr:'pluma', e:'A colorful feather fell from the parrot.' },
  { w:'Feed', tr:'alimentar', e:'We feed the chickens every morning.' },
  { w:'Feel', tr:'sentir', e:'I feel happy today.' },
  { w:'Field', tr:'campo', e:'The cows graze in the field.' },
  { w:'Fight', tr:'pelear', e:'The two brothers stopped fighting.' },
  { w:'Finger', tr:'dedo', e:'She hurt her finger playing.' },
  { w:'Finish', tr:'terminar', e:'We need to finish our homework.' },
  { w:'Firefighter', tr:'bombero', e:'The firefighter climbed the tall ladder.' },
  { w:'Fire', tr:'fuego', e:'Fire is hot and bright.' },
  { w:'First', tr:'primero', e:'She was first in line.' },
  { w:'Fish', tr:'pez', e:'The fish swims in the river.' },
  { w:'Flag', tr:'bandera', e:'They raised the flag in the morning.' },
  { w:'Flashlight', tr:'linterna', e:'We used a flashlight in the cave.' },
  { w:'Floor', tr:'piso', e:'The toys are all over the floor.' },
  { w:'Flower', tr:'flor', e:'This flower smells wonderful.' },
  { w:'Fly', tr:'volar', e:'Birds fly south in winter.' },
  { w:'Follow', tr:'seguir', e:'Follow the path to the lake.' },
  { w:'Foot', tr:'pie', e:'He hurt his foot playing soccer.' },
  { w:'Forest', tr:'bosque', e:'Many animals live in the forest.' },
  { w:'Forget', tr:'olvidar', e:'Don’t forget your backpack.' },
  { w:'Fork', tr:'tenedor', e:'Use a fork to eat the salad.' },
  { w:'Fox', tr:'zorro', e:'The fox hid behind the bushes.' },
  { w:'Free', tr:'libre', e:'The bird flew free in the sky.' },
  { w:'Friend', tr:'amigo', e:'My best friend lives next door.' },
  { w:'Frog', tr:'rana', e:'The frog jumped into the pond.' },
  { w:'Frozen', tr:'congelado', e:'The lake was frozen in winter.' },
  { w:'Fruit', tr:'fruta', e:'I eat fruit every morning.' },
  { w:'Full', tr:'lleno', e:'The basket is full of apples.' },
  { w:'Funny', tr:'gracioso', e:'That joke was really funny.' },
  { w:'Future', tr:'futuro', e:'What do you want to be in the future?' },
  { w:'Galaxy', tr:'galaxia', e:'Our galaxy has billions of stars.' },
  { w:'Garbage', tr:'basura', e:'Please put the garbage in the bin.' },
  { w:'Garden', tr:'jardín', e:'She grows flowers in the garden.' },
  { w:'Gate', tr:'portón', e:'Close the gate behind you.' },
  { w:'Gentle', tr:'gentil', e:'Be gentle with the baby bird.' },
  { w:'Gift', tr:'regalo', e:'He opened his birthday gift.' },
  { w:'Giraffe', tr:'jirafa', e:'The giraffe eats leaves from tall trees.' },
  { w:'Glass', tr:'vaso', e:'He drank a glass of water.' },
  { w:'Glue', tr:'pegamento', e:'We used glue for the art project.' },
  { w:'Goal', tr:'meta', e:'Her goal is to learn three languages.' },
  { w:'Goat', tr:'cabra', e:'The goat climbed up the rocky hill.' },
  { w:'Goodbye', tr:'adiós', e:'We say goodbye after class.' },
  { w:'Grandfather', tr:'abuelo', e:'My grandfather tells great stories.' },
  { w:'Grandmother', tr:'abuela', e:'My grandmother bakes bread every Sunday.' },
  { w:'Grape', tr:'uva', e:'I ate a bunch of grapes.' },
  { w:'Grass', tr:'pasto', e:'The grass is green after the rain.' },
  { w:'Great', tr:'genial', e:'That was a great idea!' },
  { w:'Green', tr:'verde', e:'The leaves are green in spring.' },
  { w:'Grow', tr:'crecer', e:'Plants grow with sunlight and water.' },
  { w:'Guess', tr:'adivinar', e:'Can you guess what’s in the box?' },
  { w:'Guitar', tr:'guitarra', e:'He learned to play the guitar.' },
  { w:'Habit', tr:'hábito', e:'Reading every night is a good habit.' },
  { w:'Hair', tr:'pelo', e:'Her hair is long and curly.' },
  { w:'Half', tr:'mitad', e:'Cut the apple in half.' },
  { w:'Hammer', tr:'martillo', e:'He used a hammer to fix the chair.' },
  { w:'Hand', tr:'mano', e:'Wash your hands before eating.' },
  { w:'Happy', tr:'feliz', e:'I am happy to see you.' },
  { w:'Hard', tr:'difícil', e:'This math problem is hard.' },
  { w:'Harvest', tr:'cosecha', e:'Farmers harvest wheat in summer.' },
  { w:'Hat', tr:'sombrero', e:'She wore a hat to the beach.' },
  { w:'Head', tr:'cabeza', e:'Wear a helmet to protect your head.' },
  { w:'Healthy', tr:'saludable', e:'Vegetables are healthy for you.' },
  { w:'Hear', tr:'oír', e:'Can you hear the birds singing?' },
  { w:'Heart', tr:'corazón', e:'My heart beats fast when I run.' },
  { w:'Heavy', tr:'pesado', e:'The box is too heavy to lift.' },
  { w:'Hello', tr:'hola', e:'Hello! How are you today?' },
  { w:'Help', tr:'ayudar', e:'Can you help me with this?' },
  { w:'Hen', tr:'gallina', e:'The hen laid an egg.' },
  { w:'Hide', tr:'esconder', e:'Let’s play hide and seek.' },
  { w:'Hill', tr:'colina', e:'We walked up the hill.' },
  { w:'History', tr:'historia', e:'We study history at school.' },
  { w:'Hobby', tr:'pasatiempo', e:'Drawing is her favorite hobby.' },
  { w:'Honest', tr:'honesto', e:'She was honest about the mistake.' },
  { w:'Honey', tr:'miel', e:'Bees make honey from flowers.' },
  { w:'Horse', tr:'caballo', e:'The horse runs across the field.' },
  { w:'Hospital', tr:'hospital', e:'They took him to the hospital.' },
  { w:'Hot', tr:'caliente', e:'The soup is too hot.' },
  { w:'House', tr:'casa', e:'My house has a small garden.' },
  { w:'Hug', tr:'abrazo', e:'She gave her grandmother a hug.' },
  { w:'Hundred', tr:'cien', e:'There are one hundred years in a century.' },
  { w:'Hungry', tr:'hambriento', e:'The puppy was very hungry.' },
  { w:'Hurry', tr:'apurarse', e:'Hurry up, we’re going to be late.' },
  { w:'Hurt', tr:'doler', e:'My leg hurts a little.' },
  { w:'Ice', tr:'hielo', e:'Ice is frozen water.' },
  { w:'Idea', tr:'idea', e:'I have a great idea for the project.' },
  { w:'Insect', tr:'insecto', e:'An ant is a small insect.' },
  { w:'Instrument', tr:'instrumento', e:'The violin is a musical instrument.' },
  { w:'Invent', tr:'inventar', e:'She likes to invent new games.' },
  { w:'Invite', tr:'invitar', e:'We invite our friends to the party.' },
  { w:'Island', tr:'isla', e:'Chiloé is a large island in Chile.' },
  { w:'Job', tr:'trabajo', e:'Her job is to teach children.' },
  { w:'Joke', tr:'chiste', e:'He told a funny joke.' },
  { w:'Journey', tr:'viaje', e:'Their journey took three days.' },
  { w:'Juice', tr:'jugo', e:'I drink orange juice every morning.' },
  { w:'Jump', tr:'saltar', e:'The children jump with the rope.' },
  { w:'Jungle', tr:'selva', e:'Many animals live in the jungle.' },
  { w:'Key', tr:'llave', e:'He lost the key to his house.' },
  { w:'Kick', tr:'patear', e:'She likes to kick the ball hard.' },
  { w:'Kid', tr:'niño', e:'The kids played in the park.' },
  { w:'Kind', tr:'amable', e:'The kind boy shared his lunch.' },
  { w:'King', tr:'rey', e:'The king lived in a big castle.' },
  { w:'Kiss', tr:'beso', e:'She gave her mom a kiss goodnight.' },
  { w:'Kitchen', tr:'cocina', e:'We cook dinner in the kitchen.' },
  { w:'Kite', tr:'volantín', e:'We flew a kite at the beach.' },
  { w:'Knee', tr:'rodilla', e:'He scraped his knee falling down.' },
  { w:'Knife', tr:'cuchillo', e:'Be careful with that sharp knife.' },
  { w:'Lake', tr:'lago', e:'The lake was calm and clear.' },
  { w:'Lamp', tr:'lámpara', e:'Turn off the lamp before sleeping.' },
  { w:'Language', tr:'idioma', e:'English is a useful language.' },
  { w:'Last', tr:'último', e:'This is the last piece of cake.' },
  { w:'Late', tr:'tarde', e:'We arrived a bit late.' },
  { w:'Laugh', tr:'reír', e:'Her joke made everyone laugh.' },
  { w:'Learn', tr:'aprender', e:'I learn new words every day.' },
  { w:'Leaf', tr:'hoja', e:'The leaf fell from the tree.' },
  { w:'Leg', tr:'pierna', e:'He broke his leg skiing.' },
  { w:'Letter', tr:'carta', e:'I wrote a letter to my grandma.' },
  { w:'Library', tr:'biblioteca', e:'We borrow books from the library.' },
  { w:'Light', tr:'luz', e:'Turn on the light, please.' },
  { w:'Line', tr:'línea', e:'Draw a straight line.' },
  { w:'Lion', tr:'león', e:'The lion rested under a tree.' },
  { w:'List', tr:'lista', e:'Make a list of things to buy.' },
  { w:'Listen', tr:'escuchar', e:'Listen carefully to the teacher.' },
  { w:'Live', tr:'vivir', e:'They live near the mountains.' },
  { w:'Look', tr:'mirar', e:'Look at that beautiful rainbow.' },
  { w:'Loud', tr:'ruidoso', e:'The music was too loud.' },
  { w:'Love', tr:'amor', e:'Love makes people kind.' },
  { w:'Lucky', tr:'afortunado', e:'She felt lucky to find the coin.' },
  { w:'Lunch', tr:'almuerzo', e:'We eat lunch at noon.' },
  { w:'Machine', tr:'máquina', e:'The washing machine is very loud.' },
  { w:'Magic', tr:'magia', e:'The magician performed amazing magic.' },
  { w:'Mail', tr:'correo', e:'She sent the letter by mail.' },
  { w:'Map', tr:'mapa', e:'We found Chile on the map.' },
  { w:'Market', tr:'mercado', e:'Farmers sell food at the market.' },
  { w:'Mask', tr:'máscara', e:'He wore a dragon mask for the party.' },
  { w:'Medicine', tr:'medicina', e:'She took medicine for her cold.' },
  { w:'Meet', tr:'conocer', e:'I want to meet your new friend.' },
  { w:'Melt', tr:'derretir', e:'The ice will melt in the sun.' },
  { w:'Message', tr:'mensaje', e:'She sent a message to her friend.' },
  { w:'Milk', tr:'leche', e:'I drink milk at breakfast.' },
  { w:'Mirror', tr:'espejo', e:'He looked at himself in the mirror.' },
  { w:'Mix', tr:'mezclar', e:'Mix the flour and the sugar.' },
  { w:'Monkey', tr:'mono', e:'The monkey swung from branch to branch.' },
  { w:'Month', tr:'mes', e:'March is the third month of the year.' },
  { w:'Moon', tr:'luna', e:'The moon shines at night.' },
  { w:'Morning', tr:'mañana', e:'I wake up early in the morning.' },
  { w:'Mother', tr:'madre', e:'My mother works at a hospital.' },
  { w:'Mountain', tr:'montaña', e:'The mountain is covered with snow.' },
  { w:'Mouth', tr:'boca', e:'Open your mouth for the doctor.' },
  { w:'Movie', tr:'película', e:'We watched a movie on Friday.' },
  { w:'Museum', tr:'museo', e:'We visited a science museum.' },
  { w:'Music', tr:'música', e:'We listen to music together.' },
  { w:'Name', tr:'nombre', e:'What is your name?' },
  { w:'Nature', tr:'naturaleza', e:'We must take care of nature.' },
  { w:'Neck', tr:'cuello', e:'The giraffe has a very long neck.' },
  { w:'Need', tr:'necesitar', e:'Plants need water and sunlight.' },
  { w:'Neighbor', tr:'vecino', e:'Our neighbor has a friendly dog.' },
  { w:'Nervous', tr:'nervioso', e:'She felt nervous before the test.' },
  { w:'Nest', tr:'nido', e:'The bird built a nest in the tree.' },
  { w:'New', tr:'nuevo', e:'I got a new backpack for school.' },
  { w:'News', tr:'noticias', e:'We watched the news together.' },
  { w:'Night', tr:'noche', e:'The stars come out at night.' },
  { w:'Noise', tr:'ruido', e:'The noise woke up the baby.' },
  { w:'North', tr:'norte', e:'Birds fly north in spring.' },
  { w:'Nose', tr:'nariz', e:'The dog’s nose can smell everything.' },
  { w:'Notebook', tr:'cuaderno', e:'I write notes in my notebook.' },
  { w:'Number', tr:'número', e:'Seven is my favorite number.' },
  { w:'Nurse', tr:'enfermera', e:'The nurse checked my temperature.' },
  { w:'Ocean', tr:'océano', e:'The Pacific Ocean is huge.' },
  { w:'Office', tr:'oficina', e:'My mom works in an office.' },
  { w:'Old', tr:'viejo', e:'That is a very old book.' },
  { w:'Onion', tr:'cebolla', e:'The soup has onion and carrot.' },
  { w:'Open', tr:'abrir', e:'Open the door, please.' },
  { w:'Orange', tr:'naranjo', e:'I like orange juice in the morning.' },
  { w:'Outside', tr:'afuera', e:'Let’s play outside today.' },
  { w:'Owl', tr:'lechuza', e:'The owl hunts at night.' },
  { w:'Owner', tr:'dueño', e:'The dog ran to greet its owner.' },
  { w:'Page', tr:'página', e:'Turn to the next page.' },
  { w:'Pain', tr:'dolor', e:'She felt pain in her ankle.' },
  { w:'Paint', tr:'pintar', e:'We paint pictures in art class.' },
  { w:'Paper', tr:'papel', e:'We wrote our names on paper.' },
  { w:'Parade', tr:'desfile', e:'The whole town watched the parade.' },
  { w:'Parent', tr:'padre o madre', e:'Both of my parents work at the hospital.' },
  { w:'Park', tr:'parque', e:'We play soccer at the park.' },
  { w:'Party', tr:'fiesta', e:'We had a birthday party.' },
  { w:'Path', tr:'sendero', e:'We followed the path through the forest.' },
  { w:'Patient', tr:'paciente', e:'The doctor cared for the patient.' },
  { w:'Pay', tr:'pagar', e:'He paid for the tickets.' },
  { w:'Peace', tr:'paz', e:'We work together in peace.' },
  { w:'Pencil', tr:'lápiz', e:'I draw with a pencil.' },
  { w:'Penguin', tr:'pingüino', e:'The penguin slid across the ice.' },
  { w:'Person', tr:'persona', e:'Every person is different.' },
  { w:'Photo', tr:'foto', e:'She took a photo of the sunset.' },
  { w:'Pig', tr:'cerdo', e:'The pig rolled in the mud.' },
  { w:'Pillow', tr:'almohada', e:'He fluffed up his pillow.' },
  { w:'Pilot', tr:'piloto', e:'The pilot flew the plane smoothly.' },
  { w:'Pineapple', tr:'piña', e:'The pineapple tasted very sweet.' },
  { w:'Pink', tr:'rosado', e:'Her dress was bright pink.' },
  { w:'Pirate', tr:'pirata', e:'The pirate searched for treasure.' },
  { w:'Place', tr:'lugar', e:'This is a beautiful place.' },
  { w:'Planet', tr:'planeta', e:'Mars is a red planet.' },
  { w:'Plant', tr:'planta', e:'Water the plant every day.' },
  { w:'Plate', tr:'plato', e:'She set the plate on the table.' },
  { w:'Play', tr:'jugar', e:'The children play in the yard.' },
  { w:'Please', tr:'por favor', e:'Can you help me, please?' },
  { w:'Pocket', tr:'bolsillo', e:'He kept the coin in his pocket.' },
  { w:'Poem', tr:'poema', e:'She wrote a poem about the sea.' },
  { w:'Pond', tr:'estanque', e:'Frogs live near the pond.' },
  { w:'Poor', tr:'pobre', e:'They helped the poor family.' },
  { w:'Pot', tr:'olla', e:'She cooked soup in a big pot.' },
  { w:'Pretty', tr:'bonito', e:'The garden looks pretty in spring.' },
  { w:'Prince', tr:'príncipe', e:'The prince lived in the castle.' },
  { w:'Princess', tr:'princesa', e:'The princess wore a golden crown.' },
  { w:'Prize', tr:'premio', e:'She won first prize in the contest.' },
  { w:'Problem', tr:'problema', e:'We solved the math problem together.' },
  { w:'Promise', tr:'promesa', e:'He made a promise to help her.' },
  { w:'Proud', tr:'orgulloso', e:'She felt proud of her painting.' },
  { w:'Pull', tr:'tirar', e:'Pull the rope to ring the bell.' },
  { w:'Puppy', tr:'cachorro', e:'The puppy chased its tail.' },
  { w:'Push', tr:'empujar', e:'Push the door to open it.' },
  { w:'Puzzle', tr:'rompecabezas', e:'We finished the puzzle together.' },
  { w:'Queen', tr:'reina', e:'The queen waved from the balcony.' },
  { w:'Question', tr:'pregunta', e:'She asked a good question.' },
  { w:'Quick', tr:'rápido', e:'He gave a quick answer.' },
  { w:'Quiet', tr:'silencioso', e:'The library is very quiet.' },
  { w:'Rabbit', tr:'conejo', e:'The rabbit hopped across the yard.' },
  { w:'Race', tr:'carrera', e:'They had a race around the park.' },
  { w:'Raincoat', tr:'impermeable', e:'Wear your raincoat, it’s raining.' },
  { w:'Rain', tr:'lluvia', e:'The rain falls on the roof.' },
  { w:'Rainbow', tr:'arcoíris', e:'A rainbow appeared after the rain.' },
  { w:'Reach', tr:'alcanzar', e:'She reached for the top shelf.' },
  { w:'Read', tr:'leer', e:'I read a story every night.' },
  { w:'Ready', tr:'listo', e:'Are you ready to go?' },
  { w:'Recipe', tr:'receta', e:'We followed the recipe carefully.' },
  { w:'Red', tr:'rojo', e:'The fire truck is red.' },
  { w:'Remember', tr:'recordar', e:'I remember my first day of school.' },
  { w:'Repeat', tr:'repetir', e:'Please repeat the question.' },
  { w:'Rest', tr:'descansar', e:'We need to rest after the hike.' },
  { w:'Restaurant', tr:'restaurante', e:'We ate dinner at a restaurant.' },
  { w:'Return', tr:'regresar', e:'They will return home tomorrow.' },
  { w:'Ribbon', tr:'cinta', e:'She tied a ribbon around the gift.' },
  { w:'Rice', tr:'arroz', e:'We eat rice with chicken.' },
  { w:'Right', tr:'derecha', e:'Turn right at the corner.' },
  { w:'Ring', tr:'anillo', e:'He gave her a golden ring.' },
  { w:'River', tr:'río', e:'The river flows to the sea.' },
  { w:'Road', tr:'camino', e:'The road leads to the mountains.' },
  { w:'Rock', tr:'piedra', e:'The rock was very heavy.' },
  { w:'Roof', tr:'techo', e:'Snow covered the roof.' },
  { w:'Room', tr:'habitación', e:'She cleaned her room.' },
  { w:'Root', tr:'raíz', e:'The tree’s roots grow deep.' },
  { w:'Rope', tr:'cuerda', e:'We tied the boat with a rope.' },
  { w:'Rose', tr:'rosa', e:'He gave her a red rose.' },
  { w:'Round', tr:'redondo', e:'The ball is round.' },
  { w:'Run', tr:'correr', e:'We run in the park.' },
  { w:'Sad', tr:'triste', e:'She is sad because it is raining.' },
  { w:'Safe', tr:'seguro', e:'Wear a helmet to stay safe.' },
  { w:'Salt', tr:'sal', e:'Add a little salt to the soup.' },
  { w:'Same', tr:'mismo', e:'We wore the same shirt.' },
  { w:'Sand', tr:'arena', e:'We built a castle out of sand.' },
  { w:'Save', tr:'ahorrar', e:'She saves money every month.' },
  { w:'Scared', tr:'asustado', e:'He was scared of the thunder.' },
  { w:'Scarf', tr:'bufanda', e:'She wore a warm scarf.' },
  { w:'School', tr:'escuela', e:'Our school has a big library.' },
  { w:'Science', tr:'ciencia', e:'Science explains how things work.' },
  { w:'Scissors', tr:'tijeras', e:'Cut the paper with scissors.' },
  { w:'Sea', tr:'mar', e:'The sea is calm today.' },
  { w:'Season', tr:'estación', e:'Summer is my favorite season.' },
  { w:'Sell', tr:'vender', e:'They sell fruit at the market.' },
  { w:'Send', tr:'enviar', e:'I will send you a message.' },
  { w:'Shadow', tr:'sombra', e:'His shadow followed him on the wall.' },
  { w:'Shape', tr:'forma', e:'A circle is a simple shape.' },
  { w:'Share', tr:'compartir', e:'We share our toys with friends.' },
  { w:'Sheep', tr:'oveja', e:'The sheep gave us wool.' },
  { w:'Shell', tr:'concha', e:'She found a shell on the beach.' },
  { w:'Shirt', tr:'camisa', e:'He wore a blue shirt.' },
  { w:'Shoe', tr:'zapato', e:'Tie your shoes before running.' },
  { w:'Shop', tr:'tienda', e:'We bought bread at the shop.' },
  { w:'Short', tr:'corto', e:'The story was very short.' },
  { w:'Shoulder', tr:'hombro', e:'She carried the bag on her shoulder.' },
  { w:'Shout', tr:'gritar', e:'Don’t shout indoors.' },
  { w:'Shy', tr:'tímido', e:'He was shy at first.' },
  { w:'Sick', tr:'enfermo', e:'She stayed home because she was sick.' },
  { w:'Side', tr:'lado', e:'Sit on the other side.' },
  { w:'Sign', tr:'cartel', e:'The sign showed the way to the park.' },
  { w:'Silly', tr:'tonto', e:'He told a silly joke.' },
  { w:'Silver', tr:'plateado', e:'She wore a silver necklace.' },
  { w:'Simple', tr:'simple', e:'The instructions were simple.' },
  { w:'Sing', tr:'cantar', e:'The birds sing in the trees.' },
  { w:'Sister', tr:'hermana', e:'My sister loves to paint.' },
  { w:'Skin', tr:'piel', e:'Sunscreen protects your skin.' },
  { w:'Skirt', tr:'falda', e:'She wore a yellow skirt.' },
  { w:'Sky', tr:'cielo', e:'The sky is clear today.' },
  { w:'Sleep', tr:'dormir', e:'Babies sleep many hours.' },
  { w:'Slow', tr:'lento', e:'The turtle is slow but steady.' },
  { w:'Small', tr:'pequeño', e:'The mouse is a small animal.' },
  { w:'Snow', tr:'nieve', e:'The snow covers the mountains.' },
  { w:'Soap', tr:'jabón', e:'Wash your hands with soap.' },
  { w:'Sock', tr:'calcetín', e:'He lost one sock.' },
  { w:'Soft', tr:'suave', e:'The blanket felt very soft.' },
  { w:'Soil', tr:'tierra', e:'Plants grow in rich soil.' },
  { w:'Soldier', tr:'soldado', e:'The soldier stood at attention.' },
  { w:'Son', tr:'hijo', e:'Their son plays the violin.' },
  { w:'Song', tr:'canción', e:'I know all the words to that song.' },
  { w:'Sour', tr:'agrio', e:'The lemon tasted very sour.' },
  { w:'South', tr:'sur', e:'Penguins live in the south.' },
  { w:'Speak', tr:'hablar', e:'We speak English in class.' },
  { w:'Spider', tr:'araña', e:'A spider spun its web.' },
  { w:'Spoon', tr:'cuchara', e:'She ate the soup with a spoon.' },
  { w:'Spring', tr:'primavera', e:'Flowers bloom in spring.' },
  { w:'Square', tr:'cuadrado', e:'Draw a square on the paper.' },
  { w:'Stairs', tr:'escaleras', e:'He ran up the stairs.' },
  { w:'Star', tr:'estrella', e:'A star shines far away.' },
  { w:'Stone', tr:'piedra', e:'She skipped a stone across the lake.' },
  { w:'Store', tr:'tienda', e:'We bought milk at the store.' },
  { w:'Story', tr:'cuento', e:'She told a great story.' },
  { w:'Stove', tr:'cocina', e:'She cooked soup on the stove.' },
  { w:'Street', tr:'calle', e:'Cars drive down the street.' },
  { w:'Strong', tr:'fuerte', e:'The rope is very strong.' },
  { w:'Student', tr:'estudiante', e:'Every student has a notebook.' },
  { w:'Suitcase', tr:'maleta', e:'He packed his suitcase for the trip.' },
  { w:'Summer', tr:'verano', e:'We swim a lot in summer.' },
  { w:'Sun', tr:'sol', e:'The sun rises in the east.' },
  { w:'Sunny', tr:'soleado', e:'It was a sunny afternoon.' },
  { w:'Sunrise', tr:'amanecer', e:'We watched the sunrise together.' },
  { w:'Sunset', tr:'atardecer', e:'The sunset painted the sky orange.' },
  { w:'Surprise', tr:'sorpresa', e:'They planned a surprise party.' },
  { w:'Sweet', tr:'dulce', e:'The candy tastes very sweet.' },
  { w:'Swim', tr:'nadar', e:'We swim in the pool in summer.' },
  { w:'Swing', tr:'columpio', e:'She played on the swing.' },
  { w:'Table', tr:'mesa', e:'The books are on the table.' },
  { w:'Tail', tr:'cola', e:'The dog wagged its tail.' },
  { w:'Talk', tr:'hablar', e:'Let’s talk about your day.' },
  { w:'Tall', tr:'alto', e:'The giraffe is very tall.' },
  { w:'Taste', tr:'probar', e:'Can I taste your soup?' },
  { w:'Teacher', tr:'profesor', e:'The teacher explains the lesson.' },
  { w:'Tear', tr:'lágrima', e:'A tear rolled down her cheek.' },
  { w:'Teeth', tr:'dientes', e:'Brush your teeth every night.' },
  { w:'Tent', tr:'carpa', e:'We slept in a tent under the stars.' },
  { w:'Test', tr:'prueba', e:'She studied hard for the test.' },
  { w:'Thanks', tr:'gracias', e:'Thanks for your help!' },
  { w:'Thick', tr:'grueso', e:'The book is very thick.' },
  { w:'Thin', tr:'delgado', e:'The wire is very thin.' },
  { w:'Think', tr:'pensar', e:'I need to think about my answer.' },
  { w:'Thirsty', tr:'sediento', e:'He was thirsty after the race.' },
  { w:'Throat', tr:'garganta', e:'His throat hurt from shouting.' },
  { w:'Throw', tr:'lanzar', e:'Throw the ball to me.' },
  { w:'Thumb', tr:'pulgar', e:'He gave a thumbs up.' },
  { w:'Ticket', tr:'entrada', e:'We bought a ticket for the show.' },
  { w:'Tie', tr:'corbata', e:'He wore a red tie.' },
  { w:'Tiger', tr:'tigre', e:'The tiger has orange and black stripes.' },
  { w:'Tired', tr:'cansado', e:'She was tired after the long walk.' },
  { w:'Today', tr:'hoy', e:'Today is a sunny day.' },
  { w:'Toe', tr:'dedo del pie', e:'He stubbed his toe.' },
  { w:'Together', tr:'juntos', e:'We work well together.' },
  { w:'Tomato', tr:'tomate', e:'The salad has fresh tomatoes.' },
  { w:'Tomorrow', tr:'mañana', e:'We will visit the museum tomorrow.' },
  { w:'Tongue', tr:'lengua', e:'The dog’s tongue hung out.' },
  { w:'Tool', tr:'herramienta', e:'A hammer is a useful tool.' },
  { w:'Towel', tr:'toalla', e:'She dried off with a towel.' },
  { w:'Town', tr:'pueblo', e:'They live in a small town.' },
  { w:'Toy', tr:'juguete', e:'The baby played with a toy.' },
  { w:'Train', tr:'tren', e:'We rode the train to the city.' },
  { w:'Travel', tr:'viajar', e:'They love to travel in summer.' },
  { w:'Tree', tr:'árbol', e:'The tree gives us shade.' },
  { w:'Trip', tr:'viaje', e:'Our trip to the beach was fun.' },
  { w:'True', tr:'verdadero', e:'Is this story true?' },
  { w:'Trust', tr:'confiar', e:'I trust my best friend.' },
  { w:'Truth', tr:'verdad', e:'She always tells the truth.' },
  { w:'Try', tr:'intentar', e:'Try your best on the test.' },
  { w:'Turtle', tr:'tortuga', e:'The turtle moves very slowly.' },
  { w:'Umbrella', tr:'paraguas', e:'Take an umbrella, it might rain.' },
  { w:'Uncle', tr:'tío', e:'My uncle lives near the coast.' },
  { w:'Under', tr:'debajo', e:'The cat hid under the table.' },
  { w:'Understand', tr:'entender', e:'Now I understand the lesson.' },
  { w:'Uniform', tr:'uniforme', e:'Students wear a school uniform.' },
  { w:'Unique', tr:'único', e:'Every snowflake is unique.' },
  { w:'Upset', tr:'molesto', e:'She was upset about the mistake.' },
  { w:'Vacation', tr:'vacaciones', e:'We travel during summer vacation.' },
  { w:'Vegetable', tr:'verdura', e:'Carrots are a healthy vegetable.' },
  { w:'Village', tr:'pueblo', e:'They live in a small village.' },
  { w:'Visit', tr:'visitar', e:'We visit our grandparents every month.' },
  { w:'Voice', tr:'voz', e:'She has a beautiful singing voice.' },
  { w:'Volcano', tr:'volcán', e:'The volcano is covered in snow.' },
  { w:'Wait', tr:'esperar', e:'Please wait for your turn.' },
  { w:'Wake up', tr:'despertar', e:'I wake up at seven every day.' },
  { w:'Walk', tr:'caminar', e:'We walk to school together.' },
  { w:'Wall', tr:'muro', e:'They painted the wall blue.' },
  { w:'Wallet', tr:'billetera', e:'He kept his money in his wallet.' },
  { w:'Warm', tr:'tibio', e:'The soup is nice and warm.' },
  { w:'Wash', tr:'lavar', e:'Wash your hands before dinner.' },
  { w:'Watch', tr:'reloj', e:'He wears a watch on his wrist.' },
  { w:'Water', tr:'agua', e:'Plants need water to grow.' },
  { w:'Wave', tr:'ola', e:'A big wave crashed on the shore.' },
  { w:'Weak', tr:'débil', e:'The old bridge looked weak.' },
  { w:'Wear', tr:'usar', e:'She likes to wear bright colors.' },
  { w:'Week', tr:'semana', e:'I have five classes this week.' },
  { w:'Wet', tr:'mojado', e:'His shoes got wet in the rain.' },
  { w:'Whale', tr:'ballena', e:'The whale swam near the boat.' },
  { w:'Wheel', tr:'rueda', e:'The wheel of the bike is round.' },
  { w:'White', tr:'blanco', e:'The clouds are white.' },
  { w:'Wild', tr:'salvaje', e:'Wild animals live in the forest.' },
  { w:'Win', tr:'ganar', e:'Our team wants to win the game.' },
  { w:'Wind', tr:'viento', e:'The wind moves the leaves.' },
  { w:'Window', tr:'ventana', e:'Open the window, please.' },
  { w:'Winter', tr:'invierno', e:'It snows a lot in winter.' },
  { w:'Wise', tr:'sabio', e:'The old owl looked very wise.' },
  { w:'Wish', tr:'deseo', e:'She made a wish before blowing the candles.' },
  { w:'Wolf', tr:'lobo', e:'The wolf howled at the moon.' },
  { w:'Wonderful', tr:'maravilloso', e:'We had a wonderful trip.' },
  { w:'Wood', tr:'madera', e:'The table is made of wood.' },
  { w:'Word', tr:'palabra', e:'I learned a new word today.' },
  { w:'Work', tr:'trabajar', e:'My parents work every day.' },
  { w:'World', tr:'mundo', e:'The world has many countries.' },
  { w:'Worm', tr:'gusano', e:'The bird found a worm in the grass.' },
  { w:'Worry', tr:'preocuparse', e:'Don’t worry, everything will be fine.' },
  { w:'Write', tr:'escribir', e:'I write a letter to my friend.' },
  { w:'Yard', tr:'patio', e:'The children play in the yard.' },
  { w:'Year', tr:'año', e:'This year we start second grade.' },
  { w:'Yellow', tr:'amarillo', e:'The sunflower is yellow.' },
  { w:'Yesterday', tr:'ayer', e:'We went to the park yesterday.' },
  { w:'Young', tr:'joven', e:'The young puppy loves to play.' },
  { w:'Zebra', tr:'cebra', e:'The zebra has black and white stripes.' },
  { w:'Zoo', tr:'zoológico', e:'We saw lions at the zoo.' },
];

let diccLang = 'es';
let diccVisible = [];

export function renderDiccionarioScreen(lang){
  diccLang = lang;
  const title = lang === 'es' ? '📖 Diccionario Español' : '🔤 English Dictionary';
  const sub = lang === 'es'
    ? 'Vocabulario escolar con definiciones simples. Toca 🔊 para escuchar cada palabra.'
    : 'Palabras en inglés con su traducción y un ejemplo. Toca 🔊 para escuchar la pronunciación.';
  const ph = lang === 'es' ? 'Busca una palabra…' : 'Search a word…';
  return '<div class="screen">'+
    '<p class="section-title">'+title+'</p>'+
    '<p class="section-sub">'+sub+'</p>'+
    '<input id="dicc-search" class="dicc-search" type="text" placeholder="'+ph+'" autocomplete="off" aria-label="'+ph+'">'+
    '<div id="dicc-list" class="dicc-list"></div>'+
  '</div>';
}

function normaliza(s){
  return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
}

function buildList(filtro){
  const base = diccLang === 'es' ? DICC_ES : DICC_EN;
  const f = normaliza(filtro || '');
  diccVisible = base.filter(function(entry){
    if(!f) return true;
    const clave = diccLang === 'es' ? entry.p : (entry.w + ' ' + entry.tr);
    return normaliza(clave).indexOf(f) !== -1;
  });
  let html = '';
  let lastLetter = '';
  diccVisible.forEach(function(entry, i){
    const word = diccLang === 'es' ? entry.p : entry.w;
    const letter = normaliza(word).charAt(0).toUpperCase();
    if(!f && letter !== lastLetter){
      html += '<div class="dicc-letter">'+letter+'</div>';
      lastLetter = letter;
    }
    if(diccLang === 'es'){
      html += '<div class="dicc-entry">'+
        '<div class="dicc-head"><span class="dicc-word">'+entry.p+'</span><span class="dicc-tipo">'+entry.t+'</span>'+
        '<button class="dicc-listen" onclick="diccSpeak('+i+')" aria-label="Escuchar">🔊</button></div>'+
        '<p class="dicc-def">'+entry.d+'</p>'+
        '<p class="dicc-ej">“'+entry.e+'”</p>'+
      '</div>';
    } else {
      html += '<div class="dicc-entry">'+
        '<div class="dicc-head"><span class="dicc-word">'+entry.w+'</span><span class="dicc-tipo">'+entry.tr+'</span>'+
        '<button class="dicc-listen" onclick="diccSpeak('+i+')" aria-label="Listen">🔊</button></div>'+
        '<p class="dicc-ej">“'+entry.e+'”</p>'+
      '</div>';
    }
  });
  if(!diccVisible.length){
    html = '<p class="dicc-empty">'+(diccLang === 'es' ? 'No encontramos esa palabra 🐾' : 'No results 🐾')+'</p>';
  }
  document.getElementById('dicc-list').innerHTML = html;
}

export function initDiccionario(){
  const input = document.getElementById('dicc-search');
  input.addEventListener('input', function(){ buildList(input.value); });
  buildList('');
}

export function diccSpeak(i){
  const entry = diccVisible[i];
  if(!entry) return;
  if(diccLang === 'es') speak(entry.p + '. ' + entry.d);
  else speak(entry.w + '. ' + entry.e, 'en');
}
