/* =========================================================
   Diccionario Español / English Dictionary — herramienta de
   consulta (no es un juego: sin rondas, estrellas ni XP).
   Accesible desde la pantalla de etapas (etapaMap), pensada
   como apoyo transversal a todas las etapas escolares.

   Contenido 100% curado dentro de la app (sin API externa):
   una API de diccionario no garantiza contenido apto para
   niños, requeriría conexión permanente y rompería la regla
   de "cero dependencias" del proyecto. El banco es vocabulario
   escolar de uso frecuente, con definiciones simples en
   español de Chile y ejemplos cortos.

   La voz reutiliza speak() de js/audio.js: español por defecto
   para el Diccionario Español, y speak(texto, 'en') para el
   English Dictionary (mismo mecanismo speakLang que usa
   content/ingles.js desde 5° básico).

   El botón 🔊 usa onclick="diccSpeak(i)" con un índice sobre la
   lista visible (module state), en vez de incrustar el texto en
   el atributo onclick — así ninguna definición puede romper el
   HTML por comillas (la misma restricción documentada de
   speakText en mcEngine.js, resuelta aquí por diseño).
   ========================================================= */
import { speak } from '../audio.js';

const DICC_ES = [
  { p:'Abeja', t:'sustantivo', d:'Insecto volador de rayas amarillas y negras que fabrica miel y ayuda a las flores a reproducirse.', e:'La abeja vuela de flor en flor.' },
  { p:'Abrazo', t:'sustantivo', d:'Gesto de cariño que consiste en rodear a alguien con los brazos.', e:'Le dio un abrazo a su abuela al llegar.' },
  { p:'Abuela', t:'sustantivo', d:'Madre de la madre o del padre de una persona.', e:'Mi abuela cuenta historias increíbles.' },
  { p:'Abuelo', t:'sustantivo', d:'Padre de la madre o del padre de una persona.', e:'Mi abuelo me enseñó a pescar.' },
  { p:'Agua', t:'sustantivo', d:'Líquido transparente y sin sabor que beben los seres vivos y cubre gran parte de la Tierra.', e:'Toma agua durante todo el día.' },
  { p:'Alegría', t:'sustantivo', d:'Emoción que sentimos cuando algo nos gusta o nos hace felices.', e:'Saltó de alegría con la noticia.' },
  { p:'Amable', t:'adjetivo', d:'Que trata a los demás con cariño y respeto.', e:'El vecino fue muy amable con nosotros.' },
  { p:'Amanecer', t:'sustantivo', d:'Momento del día en que empieza a salir el sol.', e:'Nos levantamos temprano para ver el amanecer.' },
  { p:'Amistad', t:'sustantivo', d:'Cariño y confianza entre personas que se quieren y se acompañan.', e:'Su amistad comenzó en el colegio.' },
  { p:'Ancho', t:'adjetivo', d:'Que tiene mucha distancia de un lado a otro.', e:'El río se hace más ancho cerca del mar.' },
  { p:'Aprender', t:'verbo', d:'Adquirir conocimientos o habilidades nuevas.', e:'Me gusta aprender cosas nuevas cada día.' },
  { p:'Araña', t:'sustantivo', d:'Animal de ocho patas que teje telarañas para atrapar insectos.', e:'La araña tejió su tela en la ventana.' },
  { p:'Árbol', t:'sustantivo', d:'Planta grande con tronco de madera, ramas y hojas.', e:'El árbol del patio da mucha sombra.' },
  { p:'Arcoíris', t:'sustantivo', d:'Arco de colores que aparece en el cielo cuando el sol ilumina la lluvia.', e:'Después de la lluvia salió un arcoíris.' },
  { p:'Arena', t:'sustantivo', d:'Conjunto de granitos muy pequeños que cubre playas y desiertos.', e:'Construimos un castillo de arena.' },
  { p:'Arroz', t:'sustantivo', d:'Cereal pequeño y blanco que se cocina en agua y se come como acompañamiento.', e:'Comimos arroz con pollo.' },
  { p:'Artista', t:'sustantivo', d:'Persona que crea obras de arte, como pinturas, música o esculturas.', e:'La artista pintó un mural enorme.' },
  { p:'Atardecer', t:'sustantivo', d:'Momento del día en que el sol se está poniendo.', e:'El atardecer pintó el cielo de naranjo.' },
  { p:'Avión', t:'sustantivo', d:'Vehículo con alas que vuela por el aire y transporta personas o cosas.', e:'Viajamos en avión a Isla de Pascua.' },
  { p:'Ayudar', t:'verbo', d:'Hacer algo por otra persona para que le resulte más fácil.', e:'Voy a ayudar a mi hermana con su tarea.' },
  { p:'Bandera', t:'sustantivo', d:'Tela de colores y símbolos que representa a un país u organización.', e:'Izamos la bandera de Chile el 18 de septiembre.' },
  { p:'Barco', t:'sustantivo', d:'Vehículo que flota y sirve para viajar o transportar cosas por el agua.', e:'El barco cruzó el canal muy temprano.' },
  { p:'Biblioteca', t:'sustantivo', d:'Lugar donde se guardan y prestan libros para leer y estudiar.', e:'Pedí dos cuentos en la biblioteca.' },
  { p:'Bombero', t:'sustantivo', d:'Persona que apaga incendios y ayuda en emergencias.', e:'El bombero rescató al gato del árbol.' },
  { p:'Bondad', t:'sustantivo', d:'Cualidad de las personas que hacen el bien y tratan bien a los demás.', e:'Su bondad se nota en cómo cuida a sus amigos.' },
  { p:'Bosque', t:'sustantivo', d:'Lugar con muchos árboles, plantas y animales.', e:'Caminamos por el bosque de araucarias.' },
  { p:'Brújula', t:'sustantivo', d:'Instrumento con una aguja que siempre apunta al norte y sirve para orientarse.', e:'Con la brújula encontramos el camino.' },
  { p:'Buscar', t:'verbo', d:'Intentar encontrar algo o a alguien.', e:'Vamos a buscar el libro en la estantería.' },
  { p:'Caballo', t:'sustantivo', d:'Animal grande de cuatro patas que se usa para montar o tirar carretas.', e:'El caballo galopó por el campo.' },
  { p:'Cabeza', t:'sustantivo', d:'Parte superior del cuerpo donde están el cerebro, los ojos y la boca.', e:'Usa casco para proteger la cabeza.' },
  { p:'Calor', t:'sustantivo', d:'Sensación de temperatura alta; energía que hace que las cosas se calienten.', e:'En el desierto hace mucho calor de día.' },
  { p:'Campana', t:'sustantivo', d:'Objeto de metal que suena cuando se lo golpea, usado para avisar algo.', e:'La campana del colegio anunció el recreo.' },
  { p:'Cangrejo', t:'sustantivo', d:'Animal marino de caparazón duro y dos grandes pinzas.', e:'El cangrejo caminó de lado por la arena.' },
  { p:'Cariño', t:'sustantivo', d:'Sentimiento de amor y ternura hacia alguien.', e:'Trata a su mascota con mucho cariño.' },
  { p:'Casa', t:'sustantivo', d:'Lugar donde vive una persona o una familia.', e:'Mi casa queda cerca de la plaza.' },
  { p:'Cebra', t:'sustantivo', d:'Animal parecido al caballo, con rayas blancas y negras.', e:'La cebra vive en manadas en África.' },
  { p:'Cerdo', t:'sustantivo', d:'Animal de granja de cuerpo rosado y hocico chato.', e:'El cerdo se revolcó en el barro.' },
  { p:'Cerebro', t:'sustantivo', d:'Órgano dentro de la cabeza que controla el cuerpo y permite pensar.', e:'El cerebro guarda todos nuestros recuerdos.' },
  { p:'Ciencia', t:'sustantivo', d:'Conjunto de conocimientos que explican cómo funciona el mundo, obtenidos observando y experimentando.', e:'La ciencia estudia desde las estrellas hasta las células.' },
  { p:'Ciudad', t:'sustantivo', d:'Lugar grande con muchas calles, edificios y personas viviendo juntas.', e:'Santiago es la ciudad más poblada de Chile.' },
  { p:'Cocinar', t:'verbo', d:'Preparar alimentos para comerlos.', e:'Aprendimos a cocinar pan amasado.' },
  { p:'Colina', t:'sustantivo', d:'Elevación del terreno más baja que una montaña.', e:'Subimos la colina para ver la puesta de sol.' },
  { p:'Compartir', t:'verbo', d:'Dar parte de lo que uno tiene a otras personas.', e:'Me gusta compartir mi colación.' },
  { p:'Comunidad', t:'sustantivo', d:'Grupo de personas que viven en un mismo lugar y comparten intereses.', e:'Toda la comunidad ayudó a limpiar la plaza.' },
  { p:'Cóndor', t:'sustantivo', d:'Ave grande de alas anchas que vive en la cordillera. Es el ave nacional de Chile.', e:'El cóndor voló muy alto sobre los Andes.' },
  { p:'Conejo', t:'sustantivo', d:'Animal pequeño de orejas largas que salta y come pasto.', e:'El conejo escondió una zanahoria.' },
  { p:'Continente', t:'sustantivo', d:'Cada una de las grandes extensiones de tierra del planeta, como América o Asia.', e:'Chile está en el continente americano.' },
  { p:'Corazón', t:'sustantivo', d:'Órgano que bombea la sangre por todo el cuerpo.', e:'El corazón late más rápido cuando corremos.' },
  { p:'Cordillera', t:'sustantivo', d:'Conjunto de montañas unidas entre sí. En Chile, la más conocida es la cordillera de los Andes.', e:'La cordillera se ve nevada en invierno.' },
  { p:'Cuaderno', t:'sustantivo', d:'Conjunto de hojas de papel unidas donde se escribe o dibuja.', e:'Anoté la tarea en mi cuaderno.' },
  { p:'Curioso', t:'adjetivo', d:'Que tiene ganas de conocer, descubrir o entender cosas nuevas.', e:'Es un niño curioso: todo lo pregunta.' },
  { p:'Delfín', t:'sustantivo', d:'Animal marino inteligente que respira aire y nada en grupos.', e:'El delfín saltó fuera del agua.' },
  { p:'Descubrir', t:'verbo', d:'Encontrar o conocer algo que no se conocía.', e:'Al mover la piedra descubrimos un caracol.' },
  { p:'Desierto', t:'sustantivo', d:'Lugar muy seco con poca lluvia y vegetación escasa. El desierto de Atacama es el más árido del mundo.', e:'Casi nunca llueve en el desierto.' },
  { p:'Dibujar', t:'verbo', d:'Representar algo con líneas y formas sobre un papel u otra superficie.', e:'Voy a dibujar a mi familia.' },
  { p:'Diccionario', t:'sustantivo', d:'Libro o herramienta donde se explica qué significan las palabras, ordenadas alfabéticamente.', e:'Busqué la palabra en el diccionario.' },
  { p:'Docena', t:'sustantivo', d:'Grupo de doce unidades de algo.', e:'Compramos una docena de huevos.' },
  { p:'Dormir', t:'verbo', d:'Descansar con los ojos cerrados, sin estar despierto.', e:'Hay que dormir bien antes del colegio.' },
  { p:'Educación', t:'sustantivo', d:'Proceso de aprender y enseñar conocimientos, habilidades y valores.', e:'La educación abre muchas puertas.' },
  { p:'Ejemplo', t:'sustantivo', d:'Caso o hecho que sirve para explicar o ilustrar algo.', e:'La profesora dio un ejemplo en la pizarra.' },
  { p:'Elefante', t:'sustantivo', d:'Animal terrestre enorme, con trompa larga y orejas grandes.', e:'El elefante usa su trompa para tomar agua.' },
  { p:'Empanada', t:'sustantivo', d:'Comida chilena hecha de masa rellena, generalmente con pino (carne, cebolla y huevo), horneada o frita.', e:'Comimos empanadas de pino en Fiestas Patrias.' },
  { p:'Energía', t:'sustantivo', d:'Capacidad para moverse, trabajar o producir cambios. La luz y el calor son formas de energía.', e:'El sol nos entrega energía todos los días.' },
  { p:'Enfermera', t:'sustantivo', d:'Persona que cuida y atiende a los enfermos en un hospital o consultorio.', e:'La enfermera midió mi temperatura.' },
  { p:'Enojo', t:'sustantivo', d:'Sentimiento de molestia o rabia frente a algo que no nos gusta.', e:'Contó hasta diez para calmar su enojo.' },
  { p:'Equipo', t:'sustantivo', d:'Grupo de personas que trabajan o juegan juntas por un objetivo común.', e:'Nuestro equipo ganó el campeonato.' },
  { p:'Escuela', t:'sustantivo', d:'Lugar donde los niños y niñas van a aprender con sus profesores.', e:'La escuela queda a dos cuadras.' },
  { p:'Esfuerzo', t:'sustantivo', d:'Energía y empeño que se pone para lograr algo, aunque cueste.', e:'Con esfuerzo terminó todo el trabajo.' },
  { p:'Estrella', t:'sustantivo', d:'Cuerpo del espacio que brilla con luz propia. El Sol es una estrella.', e:'Anoche vimos una estrella muy brillante.' },
  { p:'Estudiar', t:'verbo', d:'Dedicar tiempo a aprender o comprender algo.', e:'Hoy voy a estudiar para la prueba.' },
  { p:'Familia', t:'sustantivo', d:'Grupo de personas unidas por parentesco o cariño que se cuidan entre sí.', e:'Mi familia almuerza junta los domingos.' },
  { p:'Felicidad', t:'sustantivo', d:'Estado de ánimo de quien se siente pleno y contento.', e:'La felicidad se nota en su sonrisa.' },
  { p:'Flor', t:'sustantivo', d:'Parte colorida de muchas plantas, de donde nacen los frutos y las semillas.', e:'El copihue es la flor nacional de Chile.' },
  { p:'Frío', t:'adjetivo', d:'Que tiene poco calor o baja temperatura.', e:'El agua del mar está muy fría en invierno.' },
  { p:'Fruta', t:'sustantivo', d:'Alimento que dan algunas plantas, generalmente dulce, como la manzana o la frutilla.', e:'De colación traje fruta picada.' },
  { p:'Fuego', t:'sustantivo', d:'Luz y calor que se producen cuando algo se quema.', e:'El fuego de la chimenea calienta la casa.' },
  { p:'Fuerte', t:'adjetivo', d:'Que tiene mucha fuerza o resistencia.', e:'El elefante es un animal muy fuerte.' },
  { p:'Galaxia', t:'sustantivo', d:'Conjunto enorme de estrellas, planetas, gas y polvo. La nuestra se llama Vía Láctea.', e:'Nuestra galaxia tiene millones de estrellas.' },
  { p:'Generoso', t:'adjetivo', d:'Que comparte lo que tiene y ayuda sin esperar algo a cambio.', e:'Fue generoso y repartió sus dulces.' },
  { p:'Gigante', t:'adjetivo', d:'Mucho más grande de lo normal.', e:'Ese árbol es gigante comparado con los demás.' },
  { p:'Girasol', t:'sustantivo', d:'Planta con una flor grande y amarilla que gira siguiendo al sol.', e:'El girasol mira siempre hacia el sol.' },
  { p:'Glaciar', t:'sustantivo', d:'Gran masa de hielo que se mueve lentamente, formada por nieve acumulada durante muchos años.', e:'Los glaciares de la Patagonia son enormes.' },
  { p:'Gorila', t:'sustantivo', d:'Primate grande y fuerte que vive en selvas de África.', e:'El gorila se golpeó el pecho.' },
  { p:'Gracias', t:'expresión', d:'Palabra que se usa para agradecer algo a alguien.', e:'Muchas gracias por tu ayuda.' },
  { p:'Guitarra', t:'sustantivo', d:'Instrumento musical de cuerdas que se toca con los dedos o una púa.', e:'Mi hermano toca la guitarra todas las tardes.' },
  { p:'Helado', t:'sustantivo', d:'Postre frío y dulce hecho de leche o agua con azúcar y sabores.', e:'En verano comemos helado casi todos los días.' },
  { p:'Hermano', t:'sustantivo', d:'Persona que tiene los mismos padres que otra.', e:'Mi hermano menor aprendió a andar en bicicleta.' },
  { p:'Hielo', t:'sustantivo', d:'Agua congelada, sólida y fría.', e:'Puse hielo en el jugo para que estuviera frío.' },
  { p:'Himno', t:'sustantivo', d:'Canción solemne que representa a un país, institución o grupo.', e:'Cantamos el himno nacional en el acto.' },
  { p:'Historia', t:'sustantivo', d:'Relato de hechos; también, la ciencia que estudia el pasado de la humanidad.', e:'En historia aprendimos sobre los pueblos originarios.' },
  { p:'Hogar', t:'sustantivo', d:'Casa o lugar donde una persona vive y se siente segura y querida.', e:'No hay nada como volver al hogar.' },
  { p:'Honesto', t:'adjetivo', d:'Que dice la verdad y actúa de forma justa y correcta.', e:'Fue honesto y devolvió lo que encontró.' },
  { p:'Hormiga', t:'sustantivo', d:'Insecto pequeño y trabajador que vive en colonias organizadas.', e:'Las hormigas cargaban una hoja mucho más grande que ellas.' },
  { p:'Huaso', t:'sustantivo', d:'Hombre del campo chileno, experto jinete, que viste traje típico y participa en rodeos.', e:'El huaso arreó el ganado a caballo.' },
  { p:'Huerto', t:'sustantivo', d:'Terreno pequeño donde se cultivan verduras, frutas o hierbas.', e:'En el huerto del colegio plantamos lechugas.' },
  { p:'Huevo', t:'sustantivo', d:'Objeto ovalado que ponen las aves y otros animales, del que puede nacer una cría.', e:'Cociné dos huevos para el desayuno.' },
  { p:'Idea', t:'sustantivo', d:'Pensamiento que aparece en la mente sobre algo.', e:'Se me ocurrió una idea para el proyecto.' },
  { p:'Idioma', t:'sustantivo', d:'Lengua que habla un pueblo o país, como el español o el inglés.', e:'En Chile el idioma más hablado es el español.' },
  { p:'Igualdad', t:'sustantivo', d:'Situación en que todas las personas tienen los mismos derechos y oportunidades.', e:'La escuela promueve la igualdad entre todos los estudiantes.' },
  { p:'Imaginar', t:'verbo', d:'Formar ideas o imágenes en la mente de cosas que no están presentes.', e:'Me gusta imaginar mundos de fantasía.' },
  { p:'Ingeniero', t:'sustantivo', d:'Persona que diseña y construye máquinas, edificios, puentes u otras obras.', e:'La ingeniera diseñó el nuevo puente.' },
  { p:'Insecto', t:'sustantivo', d:'Animal pequeño de seis patas, como la hormiga o la abeja.', e:'El insecto caminaba por la hoja.' },
  { p:'Internet', t:'sustantivo', d:'Red mundial que conecta computadores y permite compartir información.', e:'Buscamos la tarea en internet.' },
  { p:'Invierno', t:'sustantivo', d:'Estación más fría del año, entre el otoño y la primavera.', e:'En invierno llueve mucho en el sur.' },
  { p:'Isla', t:'sustantivo', d:'Porción de tierra rodeada de agua por todas partes.', e:'Chiloé es una isla grande de Chile.' },
  { p:'Jardín', t:'sustantivo', d:'Terreno donde se cultivan plantas y flores para adornar.', e:'El jardín está lleno de flores en primavera.' },
  { p:'Jirafa', t:'sustantivo', d:'Animal de cuello muy largo que vive en África y come hojas de los árboles.', e:'La jirafa alcanzó las hojas más altas.' },
  { p:'Juego', t:'sustantivo', d:'Actividad que se hace para divertirse, muchas veces con reglas.', e:'Mi juego favorito es la escondida.' },
  { p:'Jugo', t:'sustantivo', d:'Líquido que se obtiene de frutas u otros alimentos.', e:'Preparé jugo de naranja natural.' },
  { p:'Justo', t:'adjetivo', d:'Que actúa dando a cada uno lo que corresponde, sin favorecer a nadie.', e:'El árbitro fue justo con los dos equipos.' },
  { p:'Laguna', t:'sustantivo', d:'Extensión de agua más pequeña que un lago, generalmente de poca profundidad.', e:'Vimos flamencos en la laguna.' },
  { p:'Lápiz', t:'sustantivo', d:'Instrumento alargado que sirve para escribir o dibujar.', e:'Saqué punta a mi lápiz.' },
  { p:'Lechuza', t:'sustantivo', d:'Ave nocturna de ojos grandes que caza de noche.', e:'La lechuza vuela sin hacer ruido.' },
  { p:'Leer', t:'verbo', d:'Mirar y comprender lo que está escrito.', e:'Antes de dormir me gusta leer un cuento.' },
  { p:'León', t:'sustantivo', d:'Animal grande y fuerte, conocido como "el rey de la selva", que vive en grupos llamados manadas.', e:'El león rugió desde lo alto de la roca.' },
  { p:'Ley', t:'sustantivo', d:'Norma que todos deben cumplir en un país, creada para vivir en orden y justicia.', e:'La ley protege los derechos de los niños.' },
  { p:'Libertad', t:'sustantivo', d:'Posibilidad de decidir y actuar por uno mismo, respetando a los demás.', e:'Los pájaros vuelan en libertad.' },
  { p:'Libro', t:'sustantivo', d:'Conjunto de hojas escritas, unidas y con tapas, que cuenta historias o entrega conocimientos.', e:'Terminé el libro en una semana.' },
  { p:'Limpio', t:'adjetivo', d:'Que no tiene suciedad ni manchas.', e:'Dejamos el patio limpio después de jugar.' },
  { p:'Liviano', t:'adjetivo', d:'Que pesa poco.', e:'La pluma es muy liviana.' },
  { p:'Luna', t:'sustantivo', d:'Cuerpo del espacio que gira alrededor de la Tierra y brilla de noche reflejando la luz del sol.', e:'La luna llena iluminaba el patio.' },
  { p:'Mano', t:'sustantivo', d:'Parte del cuerpo al final del brazo, con dedos, que usamos para tomar cosas.', e:'Se lavó las manos antes de comer.' },
  { p:'Mapa', t:'sustantivo', d:'Dibujo que representa un territorio, como un país o una ciudad, visto desde arriba.', e:'Ubicamos Chile en el mapa.' },
  { p:'Mar', t:'sustantivo', d:'Gran masa de agua salada que cubre parte de la Tierra.', e:'En verano vamos a la playa a ver el mar.' },
  { p:'Mariposa', t:'sustantivo', d:'Insecto de alas grandes y colores llamativos que antes fue oruga.', e:'Una mariposa se posó en la flor.' },
  { p:'Medianoche', t:'sustantivo', d:'Las doce de la noche, el momento central de la noche.', e:'Los fuegos artificiales empezaron a medianoche.' },
  { p:'Médico', t:'sustantivo', d:'Persona que estudia y trata las enfermedades para cuidar la salud de las personas.', e:'El médico revisó mi garganta.' },
  { p:'Mediodía', t:'sustantivo', d:'Las doce del día.', e:'Almorzamos al mediodía.' },
  { p:'Medir', t:'verbo', d:'Averiguar el tamaño, la cantidad o la duración de algo.', e:'Vamos a medir el largo de la mesa.' },
  { p:'Miedo', t:'sustantivo', d:'Sensación de temor frente a un peligro real o imaginado.', e:'Sintió miedo durante la tormenta, pero se calmó rápido.' },
  { p:'Minuto', t:'sustantivo', d:'Unidad de tiempo que dura sesenta segundos.', e:'Espera solo un minuto, ya vuelvo.' },
  { p:'Montaña', t:'sustantivo', d:'Elevación natural y grande del terreno.', e:'Subimos la montaña en dos horas.' },
  { p:'Música', t:'sustantivo', d:'Arte de combinar sonidos de forma agradable o expresiva.', e:'La música de esa canción me alegra.' },
  { p:'Nariz', t:'sustantivo', d:'Parte de la cara que sirve para respirar y oler.', e:'El perro usa su nariz para encontrar comida.' },
  { p:'Natación', t:'sustantivo', d:'Deporte que consiste en nadar, generalmente en una piscina o el mar.', e:'Practica natación dos veces por semana.' },
  { p:'Naturaleza', t:'sustantivo', d:'Todo lo que existe sin que lo haya hecho el ser humano: plantas, animales, ríos, montañas.', e:'Debemos cuidar la naturaleza.' },
  { p:'Neblina', t:'sustantivo', d:'Niebla poco densa que dificulta ver a lo lejos.', e:'La neblina cubrió el cerro en la mañana.' },
  { p:'Nube', t:'sustantivo', d:'Conjunto de gotitas de agua que flota en el cielo.', e:'Esa nube parece un conejo.' },
  { p:'Número', t:'sustantivo', d:'Símbolo que sirve para contar, medir y ordenar.', e:'El número siete es mi favorito.' },
  { p:'Nutritivo', t:'adjetivo', d:'Que aporta buenos nutrientes al cuerpo.', e:'La quinoa es un alimento muy nutritivo.' },
  { p:'Océano', t:'sustantivo', d:'Extensión enorme de agua salada, más grande que un mar. Chile mira al océano Pacífico.', e:'El océano Pacífico es el más grande del mundo.' },
  { p:'Oreja', t:'sustantivo', d:'Parte externa del cuerpo que permite escuchar.', e:'El conejo tiene las orejas muy largas.' },
  { p:'Orgullo', t:'sustantivo', d:'Satisfacción que se siente por un logro propio o de alguien querido.', e:'Sintió orgullo al terminar su proyecto.' },
  { p:'Oso', t:'sustantivo', d:'Animal grande y peludo, de patas fuertes, que puede trepar árboles.', e:'El oso pescó un salmón en el río.' },
  { p:'Otoño', t:'sustantivo', d:'Estación del año en que las hojas de muchos árboles cambian de color y caen.', e:'En otoño el parque se llena de hojas secas.' },
  { p:'Oveja', t:'sustantivo', d:'Animal de granja cubierto de lana, del que se obtiene lana y a veces leche.', e:'La oveja fue esquilada en primavera.' },
  { p:'Paciencia', t:'sustantivo', d:'Capacidad de esperar o perseverar con calma, sin enojarse.', e:'Armar el rompecabezas requiere paciencia.' },
  { p:'Paisaje', t:'sustantivo', d:'Extensión de terreno que se ve desde un lugar, con sus elementos naturales o construidos.', e:'El paisaje del lago era precioso.' },
  { p:'Palabra', t:'sustantivo', d:'Sonido o conjunto de letras que expresa una idea.', e:'Aprendí una palabra nueva hoy.' },
  { p:'Pan', t:'sustantivo', d:'Alimento hecho con harina, agua y levadura, horneado. En Chile es típica la marraqueta.', e:'Compramos pan fresco en la tarde.' },
  { p:'Pastel', t:'sustantivo', d:'Preparación dulce horneada, generalmente hecha con harina, huevos y azúcar.', e:'Hicimos un pastel de cumpleaños de chocolate.' },
  { p:'Patria', t:'sustantivo', d:'País al que una persona pertenece y siente como propio.', e:'Cantamos con orgullo por nuestra patria.' },
  { p:'Pelota', t:'sustantivo', d:'Objeto redondo que se usa para jugar, botar o lanzar.', e:'Jugamos a patear la pelota en el patio.' },
  { p:'Pescado', t:'sustantivo', d:'Animal acuático que se pesca para comer.', e:'Comimos pescado frito el viernes.' },
  { p:'Piano', t:'sustantivo', d:'Instrumento musical de teclas que produce sonido al golpear cuerdas internas.', e:'Aprendió a tocar el piano este año.' },
  { p:'Pingüino', t:'sustantivo', d:'Ave que no vuela pero nada muy bien, y vive en climas fríos.', e:'El pingüino se deslizó sobre el hielo.' },
  { p:'Planeta', t:'sustantivo', d:'Cuerpo del espacio que gira alrededor de una estrella. La Tierra es un planeta.', e:'Marte es conocido como el planeta rojo.' },
  { p:'Planta', t:'sustantivo', d:'Ser vivo que generalmente crece fijo en la tierra y fabrica su alimento con la luz del sol.', e:'Riego mi planta dos veces por semana.' },
  { p:'Playa', t:'sustantivo', d:'Terreno de arena junto al mar, un río o un lago.', e:'Construimos castillos en la playa.' },
  { p:'Policía', t:'sustantivo', d:'Persona encargada de cuidar el orden y la seguridad de las personas.', e:'La policía ayudó a cruzar la calle a los niños.' },
  { p:'Pregunta', t:'sustantivo', d:'Frase con la que se pide información sobre algo.', e:'Hice una pregunta en clases y la profesora la respondió.' },
  { p:'Primavera', t:'sustantivo', d:'Estación del año en que florecen las plantas, entre el invierno y el verano.', e:'En primavera el jardín se llena de flores.' },
  { p:'Profesor', t:'sustantivo', d:'Persona que enseña a otras en un colegio, universidad u otro lugar.', e:'El profesor explicó la materia con ejemplos.' },
  { p:'Pug', t:'sustantivo', d:'Raza de perro pequeño, de cara arrugada, hocico corto y carácter cariñoso. ¡Como Carboncito!', e:'El pug corrió feliz a saludar.' },
  { p:'Puma', t:'sustantivo', d:'Felino grande de Chile, de color café claro, también llamado león de montaña.', e:'El puma vive en la cordillera de los Andes.' },
  { p:'Queso', t:'sustantivo', d:'Alimento sólido hecho de leche cuajada.', e:'El sándwich lleva jamón y queso.' },
  { p:'Rana', t:'sustantivo', d:'Animal anfibio de piel húmeda que salta y vive cerca del agua.', e:'La rana saltó al estanque.' },
  { p:'Rápido', t:'adjetivo', d:'Que se mueve o hace algo en poco tiempo.', e:'El guepardo es el animal terrestre más rápido.' },
  { p:'Ratón', t:'sustantivo', d:'Animal pequeño de cola larga; también, dispositivo que mueve el cursor del computador.', e:'El ratón se escondió detrás del mueble.' },
  { p:'Reciclar', t:'verbo', d:'Transformar materiales usados, como el papel o el plástico, para volver a usarlos.', e:'Aprendimos a reciclar botellas y cartón.' },
  { p:'Regla', t:'sustantivo', d:'Instrumento plano con medidas que sirve para medir y trazar líneas rectas.', e:'Usé la regla para dibujar el margen.' },
  { p:'Reloj', t:'sustantivo', d:'Instrumento que sirve para saber la hora.', e:'El reloj de la sala marca las tres.' },
  { p:'Respeto', t:'sustantivo', d:'Consideración y buen trato hacia las personas, los seres vivos y las cosas.', e:'Tratamos con respeto a todos los compañeros.' },
  { p:'Río', t:'sustantivo', d:'Corriente natural de agua dulce que fluye hacia el mar, un lago u otro río.', e:'El río Biobío es uno de los más anchos de Chile.' },
  { p:'Risa', t:'sustantivo', d:'Sonido y gesto que hacemos cuando algo nos parece divertido.', e:'Su chiste nos sacó una risa a todos.' },
  { p:'Robot', t:'sustantivo', d:'Máquina programada para realizar tareas de forma automática.', e:'El robot armó las piezas solo.' },
  { p:'Salar', t:'sustantivo', d:'Terreno cubierto de una capa de sal, común en el norte de Chile.', e:'El Salar de Atacama tiene flamencos rosados.' },
  { p:'Saludable', t:'adjetivo', d:'Que hace bien a la salud.', e:'La fruta es una colación saludable.' },
  { p:'Satélite', t:'sustantivo', d:'Objeto que gira alrededor de un planeta; puede ser natural, como la Luna, o artificial, hecho por el ser humano.', e:'El satélite envía señales de televisión.' },
  { p:'Segundo', t:'sustantivo', d:'Unidad de tiempo muy breve; sesenta segundos forman un minuto.', e:'Corrió los cien metros en pocos segundos.' },
  { p:'Selva', t:'sustantivo', d:'Bosque tropical con muchísimos árboles, plantas y animales, y clima cálido y húmedo.', e:'La selva amazónica tiene una enorme variedad de especies.' },
  { p:'Semana', t:'sustantivo', d:'Período de siete días.', e:'La semana empieza el lunes.' },
  { p:'Semilla', t:'sustantivo', d:'Parte de una planta de la que puede nacer una planta nueva.', e:'Plantamos una semilla de zapallo.' },
  { p:'Serpiente', t:'sustantivo', d:'Animal reptil de cuerpo alargado, sin patas, que se desliza por el suelo.', e:'La serpiente se deslizó entre las piedras.' },
  { p:'Sol', t:'sustantivo', d:'Estrella que da luz y calor a la Tierra.', e:'El sol sale por el este cada mañana.' },
  { p:'Sombra', t:'sustantivo', d:'Zona oscura que se forma cuando algo bloquea la luz.', e:'Nos sentamos bajo la sombra del árbol.' },
  { p:'Sonrisa', t:'sustantivo', d:'Gesto alegre que se hace curvando los labios, sin llegar a reír.', e:'Me recibió con una gran sonrisa.' },
  { p:'Soñar', t:'verbo', d:'Imaginar historias mientras dormimos; también, desear algo con ilusión.', e:'Sueña con ser astrónoma.' },
  { p:'Sorpresa', t:'sustantivo', d:'Sentimiento que se produce cuando ocurre algo inesperado.', e:'Le organizaron una fiesta sorpresa.' },
  { p:'Tambor', t:'sustantivo', d:'Instrumento musical de percusión, formado por un cuerpo hueco cubierto con una membrana que se golpea.', e:'El tambor marcó el ritmo del desfile.' },
  { p:'Teléfono', t:'sustantivo', d:'Aparato que permite hablar o comunicarse con personas que están lejos.', e:'La llamó por teléfono para saludarla.' },
  { p:'Tiempo', t:'sustantivo', d:'Duración de las cosas; también se usa para hablar del clima.', e:'Nos quedó poco tiempo para terminar.' },
  { p:'Tierra', t:'sustantivo', d:'Planeta donde vivimos; también, el suelo donde crecen las plantas.', e:'La Tierra gira alrededor del Sol.' },
  { p:'Tigre', t:'sustantivo', d:'Felino grande de rayas negras y anaranjadas, que vive en Asia.', e:'El tigre nadó a través del río.' },
  { p:'Tijeras', t:'sustantivo', d:'Herramienta con dos hojas filosas que sirve para cortar papel u otros materiales.', e:'Recorté la figura con tijeras.' },
  { p:'Tortuga', t:'sustantivo', d:'Animal de caparazón duro que se mueve lentamente y puede vivir muchos años.', e:'La tortuga escondió la cabeza en su caparazón.' },
  { p:'Trabajo', t:'sustantivo', d:'Actividad que se realiza con esfuerzo para lograr o producir algo.', e:'El trabajo en equipo salió muy bien.' },
  { p:'Tren', t:'sustantivo', d:'Medio de transporte formado por vagones que avanzan sobre rieles.', e:'El tren llegó puntual a la estación.' },
  { p:'Universo', t:'sustantivo', d:'Todo lo que existe: los planetas, las estrellas, las galaxias y el espacio.', e:'El universo es inmenso y sigue expandiéndose.' },
  { p:'Útil', t:'adjetivo', d:'Que sirve para algo o ayuda a lograr un fin.', e:'Esa mochila es muy útil para el colegio.' },
  { p:'Vaca', t:'sustantivo', d:'Animal de granja que da leche y se cría también por su carne.', e:'La vaca pastaba tranquila en el potrero.' },
  { p:'Valiente', t:'adjetivo', d:'Que enfrenta el miedo o las dificultades con decisión.', e:'Fue valiente y contó la verdad.' },
  { p:'Valle', t:'sustantivo', d:'Terreno llano entre montañas, por donde a veces pasa un río.', e:'El valle central de Chile es muy fértil.' },
  { p:'Vecino', t:'sustantivo', d:'Persona que vive cerca de otra, en la misma calle o edificio.', e:'Saludamos a nuestro vecino todas las mañanas.' },
  { p:'Ventana', t:'sustantivo', d:'Abertura en una pared, con vidrio, que deja entrar luz y aire.', e:'Desde la ventana se ve la cordillera.' },
  { p:'Verano', t:'sustantivo', d:'Estación más calurosa del año, entre la primavera y el otoño.', e:'En verano vamos a la piscina.' },
  { p:'Verdad', t:'sustantivo', d:'Lo que corresponde a la realidad de los hechos.', e:'Decir la verdad genera confianza.' },
  { p:'Veterinario', t:'sustantivo', d:'Persona que cuida la salud de los animales.', e:'El veterinario revisó a mi perro.' },
  { p:'Viajar', t:'verbo', d:'Trasladarse de un lugar a otro, generalmente lejano.', e:'Queremos viajar al norte en las vacaciones.' },
  { p:'Volcán', t:'sustantivo', d:'Montaña con una abertura por donde puede salir lava, ceniza y gases desde el interior de la Tierra.', e:'El volcán Villarrica está en el sur de Chile.' },
  { p:'Zanahoria', t:'sustantivo', d:'Verdura alargada de color naranjo que crece bajo la tierra.', e:'La ensalada lleva zanahoria rallada.' },
  { p:'Zapallo', t:'sustantivo', d:'Verdura grande de cáscara dura y pulpa anaranjada, muy usada en la cocina chilena.', e:'La sopa llevaba zapallo y choclo.' },
  { p:'Zorro', t:'sustantivo', d:'Animal salvaje parecido a un perro, de hocico puntiagudo y cola larga. El zorro culpeo vive en Chile.', e:'El zorro se escondió entre los arbustos.' },
];

const DICC_EN = [
  { w:'Airplane', tr:'avión', e:'The airplane flies above the clouds.' },
  { w:'Animal', tr:'animal', e:'The zoo has many kinds of animals.' },
  { w:'Ant', tr:'hormiga', e:'The ant carries food to its nest.' },
  { w:'Apple', tr:'manzana', e:'The apple is red and sweet.' },
  { w:'Art', tr:'arte', e:'We paint in art class.' },
  { w:'Autumn', tr:'otoño', e:'Leaves fall in autumn.' },
  { w:'Baby', tr:'bebé', e:'The baby sleeps in the crib.' },
  { w:'Backpack', tr:'mochila', e:'My backpack is full of books.' },
  { w:'Beach', tr:'playa', e:'We play on the beach in summer.' },
  { w:'Bear', tr:'oso', e:'The bear caught a fish in the river.' },
  { w:'Bee', tr:'abeja', e:'The bee makes honey.' },
  { w:'Bicycle', tr:'bicicleta', e:'I ride my bicycle to the park.' },
  { w:'Big', tr:'grande', e:'The elephant is a big animal.' },
  { w:'Bird', tr:'pájaro', e:'The bird sings in the morning.' },
  { w:'Black', tr:'negro', e:'Carboncito is a black pug.' },
  { w:'Blue', tr:'azul', e:'The sky is blue today.' },
  { w:'Body', tr:'cuerpo', e:'We learn about the human body at school.' },
  { w:'Book', tr:'libro', e:'This book has many pictures.' },
  { w:'Brave', tr:'valiente', e:'The firefighter was very brave.' },
  { w:'Bread', tr:'pan', e:'We eat bread at breakfast.' },
  { w:'Bright', tr:'brillante', e:'The stars are bright tonight.' },
  { w:'Brother', tr:'hermano', e:'My brother plays the guitar.' },
  { w:'Bus', tr:'bus', e:'We take the bus to school.' },
  { w:'Butterfly', tr:'mariposa', e:'The butterfly landed on the flower.' },
  { w:'Candy', tr:'dulce', e:'She shared her candy with her friends.' },
  { w:'Careful', tr:'cuidadoso', e:'Be careful with the scissors.' },
  { w:'Cat', tr:'gato', e:'The cat sleeps on the sofa.' },
  { w:'Chair', tr:'silla', e:'Please sit on the chair.' },
  { w:'City', tr:'ciudad', e:'The city has tall buildings.' },
  { w:'Clean', tr:'limpio', e:'Keep your room clean.' },
  { w:'Clock', tr:'reloj', e:"The clock shows three o'clock." },
  { w:'Cloud', tr:'nube', e:'That cloud looks like a rabbit.' },
  { w:'Cold', tr:'frío', e:'The water is very cold.' },
  { w:'Cook', tr:'cocinar', e:'My father likes to cook on weekends.' },
  { w:'Country', tr:'país', e:'Chile is a long, narrow country.' },
  { w:'Cousin', tr:'primo', e:'My cousin visits us every summer.' },
  { w:'Cow', tr:'vaca', e:'The cow gives us milk.' },
  { w:'Cry', tr:'llorar', e:'The baby began to cry.' },
  { w:'Curious', tr:'curioso', e:'The curious cat looked inside the box.' },
  { w:'Dance', tr:'bailar', e:'They dance at the party.' },
  { w:'Dark', tr:'oscuro', e:'It gets dark early in winter.' },
  { w:'Daughter', tr:'hija', e:'Their daughter loves to paint.' },
  { w:'Desert', tr:'desierto', e:'The Atacama Desert is very dry.' },
  { w:'Dictionary', tr:'diccionario', e:'I look up new words in the dictionary.' },
  { w:'Dog', tr:'perro', e:'The dog runs in the park.' },
  { w:'Door', tr:'puerta', e:'Please close the door.' },
  { w:'Draw', tr:'dibujar', e:'I like to draw animals.' },
  { w:'Dream', tr:'soñar', e:'Last night I had a good dream.' },
  { w:'Drink', tr:'beber', e:'I drink water every day.' },
  { w:'Duck', tr:'pato', e:'The duck swims in the pond.' },
  { w:'Earth', tr:'Tierra', e:'The Earth orbits the Sun.' },
  { w:'Easy', tr:'fácil', e:'This puzzle is easy for me.' },
  { w:'Eat', tr:'comer', e:'We eat lunch at school.' },
  { w:'Elephant', tr:'elefante', e:'The elephant has a long trunk.' },
  { w:'Empty', tr:'vacío', e:'The glass is empty now.' },
  { w:'Enjoy', tr:'disfrutar', e:'We enjoy playing outside.' },
  { w:'Explore', tr:'explorar', e:"Let's explore the forest." },
  { w:'Family', tr:'familia', e:'My family is very big.' },
  { w:'Farm', tr:'granja', e:'The farm has cows and chickens.' },
  { w:'Fast', tr:'rápido', e:'The train is very fast.' },
  { w:'Father', tr:'padre', e:'My father cooks on Sundays.' },
  { w:'Fire', tr:'fuego', e:'Fire is hot and bright.' },
  { w:'Fish', tr:'pez', e:'The fish swims in the river.' },
  { w:'Flower', tr:'flor', e:'This flower smells wonderful.' },
  { w:'Forest', tr:'bosque', e:'Many animals live in the forest.' },
  { w:'Fox', tr:'zorro', e:'The fox hid behind the bushes.' },
  { w:'Free', tr:'libre', e:'The bird flew free in the sky.' },
  { w:'Friend', tr:'amigo', e:'My best friend lives next door.' },
  { w:'Fruit', tr:'fruta', e:'I eat fruit every morning.' },
  { w:'Full', tr:'lleno', e:'The basket is full of apples.' },
  { w:'Garden', tr:'jardín', e:'She grows flowers in the garden.' },
  { w:'Gift', tr:'regalo', e:'He opened his birthday gift.' },
  { w:'Giraffe', tr:'jirafa', e:'The giraffe eats leaves from tall trees.' },
  { w:'Goodbye', tr:'adiós', e:'We say goodbye after class.' },
  { w:'Grandfather', tr:'abuelo', e:'My grandfather tells great stories.' },
  { w:'Grandmother', tr:'abuela', e:'My grandmother bakes bread every Sunday.' },
  { w:'Green', tr:'verde', e:'The leaves are green in spring.' },
  { w:'Grow', tr:'crecer', e:'Plants grow with sunlight and water.' },
  { w:'Hand', tr:'mano', e:'Wash your hands before eating.' },
  { w:'Happy', tr:'feliz', e:'I am happy to see you.' },
  { w:'Hard', tr:'difícil', e:'This math problem is hard.' },
  { w:'Harvest', tr:'cosecha', e:'Farmers harvest wheat in summer.' },
  { w:'Heart', tr:'corazón', e:'My heart beats fast when I run.' },
  { w:'Heavy', tr:'pesado', e:'The box is too heavy to lift.' },
  { w:'Hello', tr:'hola', e:'Hello! How are you today?' },
  { w:'Help', tr:'ayudar', e:'Can you help me with this?' },
  { w:'Hill', tr:'colina', e:'We walked up the hill.' },
  { w:'History', tr:'historia', e:'We study history at school.' },
  { w:'Honest', tr:'honesto', e:'She was honest about the mistake.' },
  { w:'Horse', tr:'caballo', e:'The horse runs across the field.' },
  { w:'Hot', tr:'caliente', e:'The soup is too hot.' },
  { w:'House', tr:'casa', e:'My house has a small garden.' },
  { w:'Ice', tr:'hielo', e:'Ice is frozen water.' },
  { w:'Idea', tr:'idea', e:'I have a great idea for the project.' },
  { w:'Island', tr:'isla', e:'Chiloé is a large island in Chile.' },
  { w:'Jump', tr:'saltar', e:'The children jump with the rope.' },
  { w:'Kind', tr:'amable', e:'The kind boy shared his lunch.' },
  { w:'King', tr:'rey', e:'The king lived in a big castle.' },
  { w:'Kitchen', tr:'cocina', e:'We cook dinner in the kitchen.' },
  { w:'Lake', tr:'lago', e:'The lake was calm and clear.' },
  { w:'Language', tr:'idioma', e:'English is a useful language.' },
  { w:'Laugh', tr:'reír', e:'Her joke made everyone laugh.' },
  { w:'Learn', tr:'aprender', e:'I learn new words every day.' },
  { w:'Leaf', tr:'hoja', e:'The leaf fell from the tree.' },
  { w:'Light', tr:'luz', e:'Turn on the light, please.' },
  { w:'Lion', tr:'león', e:'The lion rested under a tree.' },
  { w:'Listen', tr:'escuchar', e:'Listen carefully to the teacher.' },
  { w:'Look', tr:'mirar', e:'Look at that beautiful rainbow.' },
  { w:'Love', tr:'amor', e:'Love makes people kind.' },
  { w:'Map', tr:'mapa', e:'We found Chile on the map.' },
  { w:'Meet', tr:'conocer', e:'I want to meet your new friend.' },
  { w:'Milk', tr:'leche', e:'I drink milk at breakfast.' },
  { w:'Monkey', tr:'mono', e:'The monkey swung from branch to branch.' },
  { w:'Moon', tr:'luna', e:'The moon shines at night.' },
  { w:'Morning', tr:'mañana', e:'I wake up early in the morning.' },
  { w:'Mother', tr:'madre', e:'My mother works at a hospital.' },
  { w:'Mountain', tr:'montaña', e:'The mountain is covered with snow.' },
  { w:'Museum', tr:'museo', e:'We visited a science museum.' },
  { w:'Music', tr:'música', e:'We listen to music together.' },
  { w:'Nature', tr:'naturaleza', e:'We must take care of nature.' },
  { w:'Nest', tr:'nido', e:'The bird built a nest in the tree.' },
  { w:'Night', tr:'noche', e:'The stars come out at night.' },
  { w:'Notebook', tr:'cuaderno', e:'I write notes in my notebook.' },
  { w:'Number', tr:'número', e:'Seven is my favorite number.' },
  { w:'Ocean', tr:'océano', e:'The Pacific Ocean is huge.' },
  { w:'Old', tr:'viejo', e:'That is a very old book.' },
  { w:'Open', tr:'abrir', e:'Open the door, please.' },
  { w:'Orange', tr:'naranjo', e:'I like orange juice in the morning.' },
  { w:'Paint', tr:'pintar', e:'We paint pictures in art class.' },
  { w:'Parent', tr:'padre o madre', e:'Both of my parents work at the hospital.' },
  { w:'Park', tr:'parque', e:'We play soccer at the park.' },
  { w:'Peace', tr:'paz', e:'We work together in peace.' },
  { w:'Pencil', tr:'lápiz', e:'I draw with a pencil.' },
  { w:'Penguin', tr:'pingüino', e:'The penguin slid across the ice.' },
  { w:'Planet', tr:'planeta', e:'Mars is a red planet.' },
  { w:'Plant', tr:'planta', e:'Water the plant every day.' },
  { w:'Play', tr:'jugar', e:'The children play in the yard.' },
  { w:'Please', tr:'por favor', e:'Can you help me, please?' },
  { w:'Pretty', tr:'bonito', e:'The garden looks pretty in spring.' },
  { w:'Proud', tr:'orgulloso', e:'She felt proud of her painting.' },
  { w:'Quiet', tr:'silencioso', e:'The library is very quiet.' },
  { w:'Rain', tr:'lluvia', e:'The rain falls on the roof.' },
  { w:'Rainbow', tr:'arcoíris', e:'A rainbow appeared after the rain.' },
  { w:'Read', tr:'leer', e:'I read a story every night.' },
  { w:'Red', tr:'rojo', e:'The fire truck is red.' },
  { w:'Repeat', tr:'repetir', e:'Please repeat the question.' },
  { w:'Rice', tr:'arroz', e:'We eat rice with chicken.' },
  { w:'River', tr:'río', e:'The river flows to the sea.' },
  { w:'Rock', tr:'piedra', e:'The rock was very heavy.' },
  { w:'Round', tr:'redondo', e:'The ball is round.' },
  { w:'Run', tr:'correr', e:'We run in the park.' },
  { w:'Sad', tr:'triste', e:'She is sad because it is raining.' },
  { w:'Safe', tr:'seguro', e:'Wear a helmet to stay safe.' },
  { w:'Sand', tr:'arena', e:'We built a castle out of sand.' },
  { w:'School', tr:'escuela', e:'Our school has a big library.' },
  { w:'Science', tr:'ciencia', e:'Science explains how things work.' },
  { w:'Sea', tr:'mar', e:'The sea is calm today.' },
  { w:'Season', tr:'estación', e:'Summer is my favorite season.' },
  { w:'Share', tr:'compartir', e:'We share our toys with friends.' },
  { w:'Shoe', tr:'zapato', e:'Tie your shoes before running.' },
  { w:'Short', tr:'corto', e:'The story was very short.' },
  { w:'Sing', tr:'cantar', e:'The birds sing in the trees.' },
  { w:'Sister', tr:'hermana', e:'My sister loves to paint.' },
  { w:'Sky', tr:'cielo', e:'The sky is clear today.' },
  { w:'Sleep', tr:'dormir', e:'Babies sleep many hours.' },
  { w:'Slow', tr:'lento', e:'The turtle is slow but steady.' },
  { w:'Small', tr:'pequeño', e:'The mouse is a small animal.' },
  { w:'Snow', tr:'nieve', e:'The snow covers the mountains.' },
  { w:'Son', tr:'hijo', e:'Their son plays the violin.' },
  { w:'Song', tr:'canción', e:'I know all the words to that song.' },
  { w:'Speak', tr:'hablar', e:'We speak English in class.' },
  { w:'Spring', tr:'primavera', e:'Flowers bloom in spring.' },
  { w:'Star', tr:'estrella', e:'A star shines far away.' },
  { w:'Strong', tr:'fuerte', e:'The rope is very strong.' },
  { w:'Student', tr:'estudiante', e:'Every student has a notebook.' },
  { w:'Summer', tr:'verano', e:'We swim a lot in summer.' },
  { w:'Sun', tr:'sol', e:'The sun rises in the east.' },
  { w:'Sweet', tr:'dulce', e:'The candy tastes very sweet.' },
  { w:'Swim', tr:'nadar', e:'We swim in the pool in summer.' },
  { w:'Table', tr:'mesa', e:'The books are on the table.' },
  { w:'Tall', tr:'alto', e:'The giraffe is very tall.' },
  { w:'Teacher', tr:'profesor', e:'The teacher explains the lesson.' },
  { w:'Thanks', tr:'gracias', e:'Thanks for your help!' },
  { w:'Think', tr:'pensar', e:'I need to think about my answer.' },
  { w:'Tiger', tr:'tigre', e:'The tiger has orange and black stripes.' },
  { w:'Today', tr:'hoy', e:'Today is a sunny day.' },
  { w:'Together', tr:'juntos', e:'We work well together.' },
  { w:'Tomorrow', tr:'mañana', e:'We will visit the museum tomorrow.' },
  { w:'Travel', tr:'viajar', e:'They love to travel in summer.' },
  { w:'Tree', tr:'árbol', e:'The tree gives us shade.' },
  { w:'True', tr:'verdadero', e:'Is this story true?' },
  { w:'Turtle', tr:'tortuga', e:'The turtle moves very slowly.' },
  { w:'Umbrella', tr:'paraguas', e:'Take an umbrella, it might rain.' },
  { w:'Understand', tr:'entender', e:'Now I understand the lesson.' },
  { w:'Village', tr:'pueblo', e:'They live in a small village.' },
  { w:'Volcano', tr:'volcán', e:'The volcano is covered in snow.' },
  { w:'Walk', tr:'caminar', e:'We walk to school together.' },
  { w:'Warm', tr:'tibio', e:'The soup is nice and warm.' },
  { w:'Water', tr:'agua', e:'Plants need water to grow.' },
  { w:'Week', tr:'semana', e:'I have five classes this week.' },
  { w:'White', tr:'blanco', e:'The clouds are white.' },
  { w:'Wild', tr:'salvaje', e:'Wild animals live in the forest.' },
  { w:'Wind', tr:'viento', e:'The wind moves the leaves.' },
  { w:'Window', tr:'ventana', e:'Open the window, please.' },
  { w:'Winter', tr:'invierno', e:'It snows a lot in winter.' },
  { w:'Wolf', tr:'lobo', e:'The wolf howled at the moon.' },
  { w:'Wonderful', tr:'maravilloso', e:'We had a wonderful trip.' },
  { w:'Word', tr:'palabra', e:'I learned a new word today.' },
  { w:'World', tr:'mundo', e:'The world has many countries.' },
  { w:'Write', tr:'escribir', e:'I write a letter to my friend.' },
  { w:'Year', tr:'año', e:'This year we start second grade.' },
  { w:'Yellow', tr:'amarillo', e:'The sunflower is yellow.' },
  { w:'Young', tr:'joven', e:'The young puppy loves to play.' },
  { w:'Zoo', tr:'zoológico', e:'We saw lions at the zoo.' },
];

let diccLang = 'es';
let diccVisible = [];

export function renderDiccionarioScreen(lang){
  diccLang = lang;
  const title = lang === 'es' ? '📖 Diccionario Español' : '🔤 English Dictionary';
  const sub = lang === 'es'
    ? 'Vocabulario escolar con definiciones simples. Toca 🔊 para escuchar cada palabra.'
    : 'Palabras en inglés con su traducción y un ejemplo. Toca 🔊 para escuchar la pronunciación.';
  const ph = lang === 'es' ? 'Busca una palabra…' : 'Search a word…';
  return '<div class="screen">'+
    '<p class="section-title">'+title+'</p>'+
    '<p class="section-sub">'+sub+'</p>'+
    '<input id="dicc-search" class="dicc-search" type="text" placeholder="'+ph+'" autocomplete="off" aria-label="'+ph+'">'+
    '<div id="dicc-list" class="dicc-list"></div>'+
  '</div>';
}

function normaliza(s){
  return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
}

function buildList(filtro){
  const base = diccLang === 'es' ? DICC_ES : DICC_EN;
  const f = normaliza(filtro || '');
  diccVisible = base.filter(function(entry){
    if(!f) return true;
    const clave = diccLang === 'es' ? entry.p : (entry.w + ' ' + entry.tr);
    return normaliza(clave).indexOf(f) !== -1;
  });
  let html = '';
  let lastLetter = '';
  diccVisible.forEach(function(entry, i){
    const word = diccLang === 'es' ? entry.p : entry.w;
    const letter = normaliza(word).charAt(0).toUpperCase();
    if(!f && letter !== lastLetter){
      html += '<div class="dicc-letter">'+letter+'</div>';
      lastLetter = letter;
    }
    if(diccLang === 'es'){
      html += '<div class="dicc-entry">'+
        '<div class="dicc-head"><span class="dicc-word">'+entry.p+'</span><span class="dicc-tipo">'+entry.t+'</span>'+
        '<button class="dicc-listen" onclick="diccSpeak('+i+')" aria-label="Escuchar">🔊</button></div>'+
        '<p class="dicc-def">'+entry.d+'</p>'+
        '<p class="dicc-ej">“'+entry.e+'”</p>'+
      '</div>';
    } else {
      html += '<div class="dicc-entry">'+
        '<div class="dicc-head"><span class="dicc-word">'+entry.w+'</span><span class="dicc-tipo">'+entry.tr+'</span>'+
        '<button class="dicc-listen" onclick="diccSpeak('+i+')" aria-label="Listen">🔊</button></div>'+
        '<p class="dicc-ej">“'+entry.e+'”</p>'+
      '</div>';
    }
  });
  if(!diccVisible.length){
    html = '<p class="dicc-empty">'+(diccLang === 'es' ? 'No encontramos esa palabra 🐾' : 'No results 🐾')+'</p>';
  }
  document.getElementById('dicc-list').innerHTML = html;
}

export function initDiccionario(){
  const input = document.getElementById('dicc-search');
  input.addEventListener('input', function(){ buildList(input.value); });
  buildList('');
}

export function diccSpeak(i){
  const entry = diccVisible[i];
  if(!entry) return;
  if(diccLang === 'es') speak(entry.p + '. ' + entry.d);
  else speak(entry.w + '. ' + entry.e, 'en');
}
